(function(){
  'use strict';
  const N=window.GLCNews,$=id=>document.getElementById(id),params=new URLSearchParams(location.search),editing=params.has('redazione'),articleId=params.get('id');
  let authUser, row=null,draftId=crypto.randomUUID(),cover='',thumbnail='',dirty=false,busy=false,allowed=false,generation=0,archiveGeneration=0,editorGeneration=0,offset=0,editorOffset=0;
  const message=text=>{$('page-status').textContent=text;},feedback=text=>{$('editor-feedback').textContent=text;};
  function setBusy(value){busy=value;document.querySelectorAll('#news-editor button,#news-form input,#news-form select,#news-form textarea').forEach(el=>el.disabled=value);$('news-form').setAttribute('aria-busy',String(value));}
  function coverPreview(){const img=$('edit-cover-preview');img.hidden=!cover;if(cover)img.src=cover;else img.removeAttribute('src');$('edit-cover-remove').hidden=!cover;}
  function fill(item){row=item;draftId=item?.id||crypto.randomUUID();cover=item?.cover||'';thumbnail=item?.thumbnail||'';for(const key of ['title','excerpt','body'])$('edit-'+key).value=item?.[key]||'';$('edit-category').value=item?.category||'Aggiornamenti';$('edit-featured').checked=!!item?.featured;$('edit-cover').value='';coverPreview();dirty=false;feedback('');$('editor-preview').hidden=true;$('editor-state').textContent=item?(item.status==='published'?'Pubblicato':'Bozza')+' · '+N.date(item.updated_at):'Nuova bozza';$('news-publish').textContent=item?.status==='published'?'Aggiorna pubblicazione':'Pubblica';$('news-draft').textContent=item?.status==='published'?'Ritira in bozza':'Salva bozza';$('news-reload').hidden=!item;document.querySelectorAll('.editor-item').forEach(b=>b.setAttribute('aria-current',String(b.dataset.id===item?.id)));}
  function discard(){return !dirty||confirm('Hai modifiche non salvate. Vuoi abbandonarle?');}
  function draft(status){return {id:draftId,title:$('edit-title').value,category:$('edit-category').value,excerpt:$('edit-excerpt').value,body:$('edit-body').value,featured:$('edit-featured').checked,cover,thumbnail,status};}
  async function open(id){if(busy||!discard())return;setBusy(true);const ticket=generation;try{const item=await N.get(id,true);if(ticket!==generation)return;if(!item)throw Error('Il dispaccio non è più disponibile.');fill(item);}catch(_){feedback('Non riesco ad aprire il dispaccio. Il testo nell’editor è rimasto intatto.');}finally{setBusy(false);}}
  async function editorList(reset=true){const ticket=++editorGeneration;try{const start=reset?0:editorOffset;const items=await N.list({editor:true,offset:start,limit:30});if(ticket!==editorGeneration||!allowed)return;if(reset)$('editor-items').replaceChildren();for(const item of items){const b=N.node('button','editor-item');b.type='button';b.dataset.id=item.id;b.setAttribute('aria-current',String(item.id===row?.id));b.append(N.node('strong','',item.title),N.node('span','',(item.status==='published'?'Pubblicato':'Bozza')+' · '+N.date(item.updated_at)));b.onclick=()=>open(item.id);$('editor-items').append(b);}editorOffset=start+items.length;$('editor-more').hidden=items.length<30;}catch(_){feedback('L’elenco dei dispacci non è raggiungibile. Riprova ricaricando la pagina.');}}
  async function save(status){if(busy||!allowed)return;if(!$('news-form').reportValidity())return;const value=draft(status);try{N.validate(value);}catch(e){feedback(e.message);return;}if(status==='published'&&!confirm(row?.status==='published'?'Aggiornare la notizia visibile a tutti?':'Pubblicare questo dispaccio per tutti i visitatori?'))return;if(status==='draft'&&row?.status==='published'&&!confirm('Ritirare questo dispaccio dal giornale pubblico? Resterà nella redazione.'))return;
    setBusy(true);feedback('Salvataggio in corso…');const ticket=generation;try{const saved=await N.save(value,row?.version);if(ticket!==generation)return;fill(saved);feedback(status==='published'?'Dispaccio pubblicato. È visibile nella Home e nel giornale.':'Bozza salvata. È visibile solo alla redazione.');await editorList();}catch(e){feedback(e.message?.includes('dispaccio è cambiato')?e.message:'Salvataggio non confermato. Il testo è ancora qui: copialo prima di ricaricare e controlla l’elenco per verificare se il salvataggio è arrivato.');$('news-reload').hidden=false;}finally{setBusy(false);}}
  async function makeThumbnail(source){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>{const canvas=document.createElement('canvas'),s=Math.min(1,640/Math.max(img.width,img.height));canvas.width=Math.round(img.width*s);canvas.height=Math.round(img.height*s);const ctx=canvas.getContext('2d');if(!ctx){reject(Error('Anteprima non disponibile'));return;}ctx.drawImage(img,0,0,canvas.width,canvas.height);const result=canvas.toDataURL('image/webp',.78);if(result.length>400000){reject(Error('Copertina troppo complessa. Scegli un’immagine più leggera.'));return;}resolve(result);};img.onerror=()=>reject(Error('Immagine non leggibile'));img.src=source;});}
  $('news-form').addEventListener('input',()=>{dirty=true;});
  $('news-form').addEventListener('submit',e=>{e.preventDefault();save('draft');});$('news-publish').onclick=()=>save('published');
  $('news-new').onclick=()=>{if(!busy&&discard()){fill(null);$('edit-title').focus();}};
  $('news-reload').onclick=()=>open(row?.id||draftId);$('editor-more').onclick=()=>editorList(false);
  $('news-preview').onclick=()=>{const box=$('editor-preview');box.hidden=false;box.replaceChildren(N.article({...draft('draft'),published_at:row?.published_at}));box.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});};
  $('edit-cover').onchange=async()=>{const file=$('edit-cover').files[0];if(!file)return;setBusy(true);feedback('Preparo la copertina…');const ticket=generation;try{const next=await GLCImages.read(file),thumb=await makeThumbnail(next);if(ticket!==generation)return;cover=next;thumbnail=thumb;coverPreview();dirty=true;feedback('Copertina pronta. Salva il dispaccio per conservarla.');}catch(e){feedback(e.message||'Caricamento non riuscito.');}finally{$('edit-cover').value='';setBusy(false);}};
  $('edit-cover-remove').onclick=()=>{cover='';thumbnail='';dirty=true;coverPreview();};
  window.addEventListener('beforeunload',e=>{if(dirty||busy){e.preventDefault();e.returnValue='';}});
  async function archive(reset=true){const ticket=++archiveGeneration,start=reset?0:offset;$('news-more').disabled=true;try{const items=await N.list({offset:start,category:$('news-category').value,limit:9});if(ticket!==archiveGeneration)return;if(reset)$('archive-items').replaceChildren();$('archive-items').append(...items.map(N.card));offset=start+items.length;$('news-more').hidden=items.length<9;message(offset?'':'Nessun dispaccio in questa rotta. Torna presto per le novità.');}catch(_){message('Il giornale non è raggiungibile. Controlla la connessione e riprova.');}finally{if(ticket===archiveGeneration)$('news-more').disabled=false;}}
  $('news-more').onclick=()=>archive(false);$('news-category').onchange=()=>archive(true);
  async function capabilities(){const ticket=++generation;allowed=false;$('news-editor-link').hidden=true;if(editing){$('news-editor').hidden=true;$('news-archive').hidden=true;message('Verifico l’accesso alla redazione…');}
    const yes=await N.canEdit();if(ticket!==generation)return;allowed=yes;$('news-editor-link').hidden=!yes||editing;
    if(editing){if(!yes){fill(null);$('editor-items').replaceChildren();message('La redazione è riservata all’amministratore. Accedi con il tuo account oppure torna al giornale.');return;}$('news-editor').hidden=false;message('');if(!$('news-form').dataset.ready){fill(null);$('news-form').dataset.ready='true';}await editorList();}
  }
  if(window.__glcSB){window.__glcSB.auth.onAuthStateChange((event,session)=>{const next=session?.user?.id||null;if(event==='SIGNED_OUT'||(authUser!==undefined&&authUser!==next)){++generation;allowed=false;$('news-editor').hidden=true;fill(null);delete $('news-form').dataset.ready;$('editor-items').replaceChildren();}authUser=next;if(event==='TOKEN_REFRESHED'||dirty||busy)return;setTimeout(capabilities,0);});}capabilities();
  if(!editing){if(articleId){$('news-archive').hidden=true;if(!/^[0-9a-f-]{36}$/i.test(articleId)){message('Questo dispaccio non esiste.');}else N.get(articleId).then(item=>{if(!item){message('Questo dispaccio non è disponibile o non è ancora pubblico.');return;}message('');const back=N.node('a','text-link','← Tutti i dispacci');back.href='/notizie/';$('news-reader').replaceChildren(back,N.article(item));document.title=item.title+' · Grand Line Chronicles';}).catch(()=>message('Non riesco a leggere il dispaccio. Riprova più tardi.'));}else{$('news-filters').hidden=false;archive();}}
})();
