(function(){
 'use strict';const T=GLCTactical,root=document.getElementById('tactical-app'),sid=new URLSearchParams(location.search).get('s');
 let expected=null,state=null,selected='',board=null,mode='move',history=[],channel=null,publisher=null,sharing=false,heartbeat=null,publishTimer=null,localLive=false,busyShare=false,shareAgain=false,dead=false;
 const localId=T.uid();const E=(tag,attrs={},kids=[])=>{const n=document.createElement(tag);for(const [k,v]of Object.entries(attrs)){if(k==='text')n.textContent=v;else if(k.startsWith('on'))n.addEventListener(k.slice(2),v);else if(k==='class')n.className=v;else n.setAttribute(k,v);}kids.filter(Boolean).forEach(c=>n.append(c));return n;};
 const B=(label,fn,cls='')=>E('button',{type:'button',text:label,class:cls,onclick:fn});
 const input=(label,value,change,opts={})=>{const box=E('div'),id='i-'+T.uid(),n=E(opts.tag||'input',{id,...opts});delete n.tag;if(opts.type!=='file')n.value=value??'';n.onchange=()=>change(n.value,n);box.append(E('label',{for:id,class:'tb-label',text:label}),n);return box;};
 const active=()=>state.scenes.find(s=>s.id===state.activeId)||state.scenes[0];
 const publicScene=()=>T.project(state.scenes.find(s=>s.id===state.presentedId));
 let status,scenes,inspector,sceneName,boardHost,roster,settings,liveButton,shareButton,linkBox;
 function notice(text,err=false){status.textContent=text;status.className='tb-status'+(err?' error':'');}
 function read(key){return JSON.parse(localStorage.getItem(key)||'null');}
 function commit(fn,{undo=true,fit=false}={}){const previous=T.clone(state),next=T.clone(state);try{fn(next);state=T.saveSession(sid,expected,next);expected=T.clone(state);if(undo){history.push(previous);if(history.length>12)history.shift();}render();if(fit)board.fit();broadcast();schedulePublish();notice('Salvato · 1 casella = 1 metro');return true;}catch(e){notice(e.message,true);return false;}}
 function mutateScene(fn,opts){return commit(n=>fn(n.scenes.find(s=>s.id===n.activeId)),opts);}
 function selectedToken(){return active().tokens.find(t=>t.id===selected);}
 function broadcast(){if(channel)channel.postMessage({kind:'scene',scene:localLive?publicScene():null});}
 function schedulePublish(){if(!sharing)return;clearTimeout(publishTimer);publishTimer=setTimeout(publish,300);}
 async function publish(){if(!sharing||!publisher)return;if(busyShare){shareAgain=true;return;}busyShare=true;const snapshot=publicScene();try{await publisher.publish(snapshot);if(sharing)notice('Salvato · scena condivisa con la ciurma');}catch(e){sharing=false;shareButton.textContent='Collega la campagna';notice(e.message+' La vista remota si chiuderà entro 45 secondi.',true);}finally{busyShare=false;if(shareAgain&&sharing){shareAgain=false;publish();}}}
 function render(){const s=active();sceneName.textContent=s.name;scenes.replaceChildren();for(const x of state.scenes){const b=B(x.name,()=>{selected='';commit(n=>n.activeId=x.id,{undo:false,fit:true});});b.setAttribute('aria-pressed',String(x.id===s.id));if(x.id===state.presentedId)b.append(E('small',{text:'IN SCENA'}));scenes.append(b);}board.render(s,selected);roster.replaceChildren();s.tokens.forEach(t=>{const b=B((t.visible?'':'◌ ')+t.name,()=>{selected=t.id;render();});b.setAttribute('aria-pressed',String(t.id===selected));roster.append(b);});
  document.getElementById('undo').disabled=!history.length;liveButton.textContent=s.id===state.presentedId?'Scena attuale in onda':'Metti questa scena in onda';renderInspector();renderSettings();
 }
 function renderSettings(){const s=active();settings.replaceChildren();settings.append(input('Nome pubblico della scena',s.name,v=>mutateScene(x=>x.name=v.trim().slice(0,100)||'Scena'),{maxlength:100}));const dim=E('div',{class:'tb-fields'});for(const [k,l]of [['cols','Larghezza · metri'],['rows','Altezza · metri']])dim.append(input(l,s[k],v=>mutateScene(x=>{x[k]=Math.max(6,Math.min(100,Math.round(+v||20)));x.tokens=T.normalize(x).tokens;},{fit:true}),{type:'number',min:6,max:100}));settings.append(dim);
  const file=E('input',{type:'file',accept:'image/png,image/jpeg,image/webp',hidden:''});settings.append(file,B(s.background?'Sostituisci sfondo':'Carica sfondo · fino a 4K',()=>file.click(),'block'));file.onchange=async()=>{const sceneId=s.id;const f=file.files[0];if(!f)return;notice('Preparo lo sfondo…');try{const image=await GLCImages.read(f);commit(n=>{const x=n.scenes.find(x=>x.id===sceneId);if(!x)throw Error('La scena non esiste più.');x.background=image;});}catch(e){notice(e.message,true);}};
  if(s.background)settings.append(B('Rimuovi sfondo',()=>mutateScene(x=>x.background=''),'block'));
  settings.append(input('Visibilità della griglia',s.gridOpacity,v=>mutateScene(x=>x.gridOpacity=+v),{type:'range',min:0,max:.7,step:.05}));
  const align=E('details');align.append(E('summary',{text:'Allinea sfondo e griglia'}));align.append(input('Scala dello sfondo',s.backgroundScale,v=>mutateScene(x=>x.backgroundScale=Math.max(.1,Math.min(5,+v||1))),{type:'number',min:.1,max:5,step:.05}));const offset=E('div',{class:'tb-fields'});for(const [k,l]of [['backgroundX','Sposta X · m'],['backgroundY','Sposta Y · m']])offset.append(input(l,s[k],v=>mutateScene(x=>x[k]=Math.max(-100,Math.min(100,+v||0))),{type:'number',min:-100,max:100,step:.25}));align.append(offset);settings.append(align,E('p',{class:'tb-note',text:'La griglia misura sempre metri. Scala e sposta lo sfondo per far coincidere porte e distanze.'}));
 }
 function renderInspector(){inspector.replaceChildren();const t=selectedToken();inspector.append(E('span',{class:'tb-private',text:'Solo Game Master'}),E('h2',{text:t?t.name:'La regia della scena'}));if(!t){inspector.append(E('p',{class:'tb-note',text:'Scegli una pedina dal campo o dall’elenco. Puoi trascinarla oppure usare le frecce della tastiera. I nemici nuovi sono nascosti finché non li riveli.'}));return;}
  const edit=fn=>mutateScene(s=>{const x=s.tokens.find(x=>x.id===t.id);if(x)fn(x);});
  inspector.append(input('Nome privato',t.name,v=>edit(x=>x.name=v.trim().slice(0,100)||'Pedina'),{maxlength:100}),input('Nome mostrato ai giocatori',t.label,v=>edit(x=>x.label=v.trim().slice(0,60)||'Pedina'),{maxlength:60}));
  const faction=E('select',{'aria-label':'Schieramento'});[['pc','Personaggio'],['ally','Alleato'],['enemy','Avversario']].forEach(([v,n])=>faction.append(E('option',{value:v,text:n})));faction.value=t.side;faction.onchange=()=>edit(x=>x.side=faction.value);const fl=E('label',{class:'tb-label',text:'Schieramento'});fl.append(faction);inspector.append(fl);
  const check=E('input',{type:'checkbox'});check.checked=t.visible;check.onchange=()=>edit(x=>x.visible=check.checked);inspector.append(E('label',{class:'tb-check'},[check,E('span',{text:'Visibile ai giocatori'})]));
  const coords=E('div',{class:'tb-fields'});for(const [k,l,max]of [['x','Colonna',active().cols-t.size],['y','Riga',active().rows-t.size]])coords.append(input(l,t[k]+1,v=>edit(x=>x[k]=Math.max(0,Math.min(max,(+v||1)-1))),{type:'number',min:1,max:max+1}));inspector.append(coords,input('Ingombro · caselle per lato',t.size,v=>edit(x=>{x.size=Math.max(1,Math.min(6,Math.round(+v||1)));x.x=Math.min(x.x,active().cols-x.size);x.y=Math.min(x.y,active().rows-x.size);}),{type:'number',min:1,max:6}));
  const file=E('input',{type:'file',accept:'image/png,image/jpeg,image/webp',hidden:''});file.onchange=async()=>{if(!file.files[0])return;const sceneId=active().id;notice('Preparo la pedina…');try{const value=await GLCImages.read(file.files[0]);commit(n=>{const target=n.scenes.find(s=>s.id===sceneId)?.tokens.find(x=>x.id===t.id);if(!target)throw Error('Pedina non più disponibile');target.image=value;});}catch(e){notice(e.message,true);}};inspector.append(file,B('Carica immagine pedina',()=>file.click(),'block'));if(t.image)inspector.append(B('Usa le iniziali',()=>edit(x=>x.image=''),'block'));
  inspector.append(input('Appunti privati',t.note,v=>edit(x=>x.note=v.slice(0,2000)),{tag:'textarea',maxlength:2000}));
  if(t.source?.kind==='fight'){const c=read('glc_scontro_v1')?.list?.find(x=>x.id===t.source.id);inspector.append(E('div',{class:'tb-statlist',text:c?`${c.nome}\nPV ${c.pvCur} / ${c.pvMax} · ST ${c.stCur} / ${c.stMax}\nDifesa ${c.difesa} · ${c.cond?.join(', ')||'Nessuno stato'}`:'Questo combattente non è più nello scontro.'}),E('a',{class:'tb-action',href:'/plancia-master/',target:'_blank',rel:'noopener',text:'Apri la Plancia ↗'}));}
  inspector.append(B('Duplica pedina',()=>{const c=T.clone(t);c.id=T.uid();c.name+=' · copia';c.x=Math.min(active().cols-c.size,c.x+1);c.visible=false;addToken(c);},'block'),B('Rimuovi dalla scena',()=>{if(mutateScene(s=>s.tokens=s.tokens.filter(x=>x.id!==t.id))){selected='';render();}},'block'));
 }
 function dialog(title){const d=E('dialog',{class:'tb-dialog'}),body=E('div');d.append(E('h2',{text:title}),body,B('Chiudi',()=>d.close()));d.addEventListener('close',()=>d.remove());document.body.append(d);d.showModal();return{d,body};}
 function addToken(t){if(active().tokens.length>=100){notice('La scena contiene già 100 pedine.',true);return;}const a=active(),cx=Math.floor(a.cols/3),cy=Math.floor(a.rows/3);let placed=false;for(let radius=0;radius<Math.max(a.cols,a.rows)&&!placed;radius++){for(let y=Math.max(0,cy-radius);y<=Math.min(a.rows-t.size,cy+radius)&&!placed;y++)for(let x=Math.max(0,cx-radius);x<=Math.min(a.cols-t.size,cx+radius);x++){if(!a.tokens.some(p=>x<p.x+p.size&&x+t.size>p.x&&y<p.y+p.size&&y+t.size>p.y)){t.x=x;t.y=y;placed=true;break;}}}if(mutateScene(s=>s.tokens.push(t))){selected=t.id;render();}}
 function picker(){const {d,body}=dialog('Porta una pedina in scena');body.append(B('+ Avversario libero',()=>{addToken(T.token({name:'Nuovo avversario',label:'Avversario '+(active().tokens.filter(t=>t.side==='enemy').length+1),side:'enemy'}));d.close();},'block'),B('+ Alleato libero',()=>{addToken(T.token({name:'Nuovo alleato',label:'Alleato',side:'ally',visible:true}));d.close();},'block'));
  const list=E('div',{class:'tb-picker'});body.append(E('p',{class:'tb-label',text:'Dallo scontro della Plancia'}),list);const f=read('glc_scontro_v1')?.list||[];if(!f.length)list.append(E('p',{class:'tb-note',text:'Aggiungi combattenti dalla Plancia per ritrovarli qui.'}));f.forEach(c=>list.append(B(c.nome,()=>{addToken(T.token({name:c.nome,label:c.side==='pc'?c.nome:'Avversario '+(active().tokens.filter(t=>t.side==='enemy').length+1),side:c.side==='pc'?'pc':'enemy',visible:c.side==='pc',source:{kind:'fight',id:c.id}}));d.close();})));
  body.append(E('p',{class:'tb-label',text:'I tuoi pirati'}));const chars=read('glc_pirata_v4')?.chars||{};Object.entries(chars).forEach(([id,c])=>body.append(B(c.nome||'Pirata',()=>{addToken(T.token({name:c.nome||'Pirata',label:c.nome||'Pirata',side:'pc',visible:true,image:T.image(c.photo),source:{kind:'character',id}}));d.close();})));
  body.append(E('p',{class:'tb-note',text:'Per i PG della ciurma puoi creare una pedina libera e caricare il ritratto. Non accediamo ai loro salvataggi privati.'}));
 }
 function localView(){if(!window.BroadcastChannel){notice('Il secondo schermo richiede un browser aggiornato.',true);return;}if(!state.presentedId&&!commit(n=>n.presentedId=n.activeId,{undo:false}))return;if(!channel){channel=new BroadcastChannel('glc-battle-'+localId);channel.onmessage=e=>{if(e.data?.kind==='hello')broadcast();};}localLive=true;broadcast();notice('Secondo schermo collegato. La vista giocatori segue la scena in onda.');}
 async function share(){if(sharing){try{sharing=false;clearTimeout(publishTimer);await publisher.close();notice('Condivisione con la campagna terminata.');}catch(e){notice('Collegamento interrotto: la vista remota si chiuderà entro 45 secondi.',true);}shareButton.textContent='Collega la campagna';return;}const sb=window.__glcSB;if(!sb){notice('Accedi per condividere con la campagna.',true);return;}
  const {d,body}=dialog('Condividi con la tua ciurma');body.append(E('p',{class:'tb-note',text:'La ciurma vedrà solo la scena in onda. PV, Stamina, statistiche, appunti e pedine nascoste non vengono condivisi.'}));try{const auth=await sb.auth.getUser();if(auth.error||!auth.data?.user)throw Error('Accedi per continuare.');const user=auth.data.user.id,r=await sb.from('campaigns').select('id,name').eq('gm',user);if(r.error)throw r.error;if(!r.data?.length){body.append(E('p',{text:'Non hai ancora una campagna come GM. Creala da Campagne.'}));return;}const select=E('select',{'aria-label':'Campagna da condividere'});r.data.forEach(c=>select.append(E('option',{value:c.id,text:c.name})));select.value=r.data.some(c=>c.id===state.campaignId)?state.campaignId:r.data[0].id;body.append(select);const start=B('Mostra alla ciurma',async()=>{start.disabled=true;try{if(!commit(n=>{if(n.campaignId!==select.value){n.campaignId=select.value;n.roomId=T.uid();}n.presentedId=n.activeId;},{undo:false}))return;publisher=GLCTacticalShare.publisher(sb,state.roomId,state.campaignId,user);await publisher.publish(publicScene());sharing=true;shareButton.textContent='Interrompi condivisione';linkBox.hidden=false;linkBox.value=location.origin+'/campo-di-battaglia/?room='+state.roomId;notice('La scena è condivisa con i membri della campagna.');d.close();}catch(e){const p=E('p',{class:'tb-status error',role:'alert',text:e.message+'. Se il servizio non è ancora attivo, usa il secondo schermo.'});body.append(p);}finally{start.disabled=false;}},'primary block');body.append(start);}catch(e){body.append(E('p',{class:'tb-status error',text:e.message}));}
 }
 function build(session){root.replaceChildren();const top=E('header',{class:'tb-top'}),titles=E('div');titles.append(E('a',{href:'/sessioni/?s='+encodeURIComponent(sid),class:'tb-brand',text:'‹ Grand Line Chronicles · '+(session.nome||'Sessione')}),E('h1',{class:'tb-title',text:'Il tavolo tattico'}),E('p',{class:'tb-sub',text:'Prepara la scena. Raduna la ciurma. Muovi la storia.'}));const actions=E('div',{class:'tb-top-actions'});shareButton=B('Collega la campagna',share);const localLink=E('a',{class:'tb-action',href:'/campo-di-battaglia/#local='+localId,target:'_blank',rel:'noopener',text:'Apri vista giocatori',onclick:e=>{if(!window.BroadcastChannel){e.preventDefault();notice('Usa un browser aggiornato per il secondo schermo.',true);return;}localView();}});actions.append(localLink,shareButton);top.append(titles,actions);root.append(top);
  status=E('p',{class:'tb-status',role:'status',text:'1 casella = 1 metro · Il controllo delle pedine è del GM'});root.append(status);linkBox=E('input',{readonly:'',hidden:'','aria-label':'Link riservato alla ciurma'});linkBox.onclick=()=>linkBox.select();root.append(linkBox);
  const layout=E('div',{class:'tb-layout'}),side=E('aside',{class:'tb-sidebar','aria-label':'Scene e ambientazione'});side.append(E('h2',{text:'Le tue scene'}));scenes=E('div',{class:'tb-scenes'});side.append(scenes,B('+ Nuova scena',()=>{if(state.scenes.length>=20)return notice('Puoi preparare fino a 20 scene per sessione.',true);const x=T.scene('Scena '+(state.scenes.length+1));selected='';commit(n=>{n.scenes.push(x);n.activeId=x.id;},{fit:true});},'block'),B('Duplica scena',()=>{if(state.scenes.length>=20)return notice('Limite di 20 scene raggiunto.',true);const x=T.clone(active());x.id=T.uid();x.name+=' · copia';x.tokens.forEach(t=>t.id=T.uid());commit(n=>{n.scenes.push(x);n.activeId=x.id;},{fit:true});},'block'),B('Rimuovi scena',()=>{if(state.scenes.length===1)return notice('Conserva almeno una scena.',true);if(!confirm('Rimuovere questa scena? Puoi usare Annulla per recuperarla.'))return;commit(n=>{const id=n.activeId;n.scenes=n.scenes.filter(s=>s.id!==id);n.activeId=n.scenes[0].id;if(n.presentedId===id)n.presentedId='';},{fit:true});},'block'),E('hr',{class:'tb-divider'}));
  const settingsDisclosure=E('details');if(innerWidth>700)settingsDisclosure.open=true;settingsDisclosure.append(E('summary',{text:'Ambientazione e griglia'}));settings=E('div');settingsDisclosure.append(settings);side.append(settingsDisclosure);
  const stage=E('section',{class:'tb-stage'}),stageHead=E('div',{class:'tb-stage-head'});sceneName=E('h2');const tools=E('div',{class:'tb-tools'}),move=B('Muovi',()=>{mode='move';move.setAttribute('aria-pressed','true');measure.setAttribute('aria-pressed','false');}),measure=B('Misura',()=>{mode='measure';move.setAttribute('aria-pressed','false');measure.setAttribute('aria-pressed','true');});move.setAttribute('aria-pressed','true');measure.setAttribute('aria-pressed','false');const undo=B('↶ Annulla',()=>{const prev=history.pop();if(!prev)return;const current=T.clone(state);if(!commit(n=>{const room=n.roomId,campaign=n.campaignId;Object.assign(n,prev);n.roomId=room;n.campaignId=campaign;},{undo:false})){history.push(prev);state=current;}render();});undo.id='undo';tools.append(move,measure,undo,B('Schermo intero',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await root.requestFullscreen();board.fit();}catch(e){notice('Schermo intero non disponibile.',true);}}));stageHead.append(sceneName,tools);boardHost=E('div');stage.append(stageHead,boardHost);board=GLCTacticalBoard.mount(boardHost,{mode:()=>mode,onSelect:id=>{selected=id;render();},onMove:(id,x,y)=>{selected=id;mutateScene(s=>{const t=s.tokens.find(t=>t.id===id);if(t){t.x=x;t.y=y;}});boardHost.querySelector('[data-token="'+CSS.escape(id)+'"]')?.focus({preventScroll:true});}});
  const bottom=E('div',{class:'tb-top-actions',style:'margin-top:14px'});liveButton=B('Metti questa scena in onda',()=>{if(commit(n=>n.presentedId=n.activeId,{undo:false})){localLive=!!channel;broadcast();notice('I giocatori vedono ora questa scena.');}},'primary');bottom.append(B('+ Aggiungi pedina',picker),liveButton,B('Oscura ai giocatori',()=>{commit(n=>n.presentedId='',{undo:false});notice('Campo oscurato ai giocatori.');}));roster=E('div',{class:'tb-roster','aria-label':'Pedine nella scena'});stage.append(bottom,roster,E('p',{class:'tb-note',text:'Misure geometriche di supporto: portate, diagonali ed effetti restano sotto la regia del GM. Le pedine tratteggiate sono visibili soltanto a te.'}));inspector=E('aside',{class:'tb-inspector','aria-label':'Dettagli privati della pedina'});layout.append(side,stage,inspector);root.append(layout);render();
 }
 function init(){try{const session=T.readSession(sid);expected=session.tactical||null;state=expected?T.clone(expected):T.empty();if(!Array.isArray(state.scenes)||!state.scenes.length)throw Error('Archivio del tavolo non valido: nessun dato è stato sostituito.');state.scenes=state.scenes.map(T.normalize);build(session);heartbeat=setInterval(()=>{if(dead)return;broadcast();if(sharing)publish();},10000);}catch(e){root.replaceChildren(E('h1',{class:'tb-title',text:'Il tavolo non è disponibile'}),E('p',{text:e.message}),E('a',{href:'/profilo/',text:'Torna al Profilo'}));}}
 window.addEventListener('storage',e=>{try{if(e.key==='glc_sessioni_v1'&&state){const newer=T.readSession(sid).tactical||null;if(JSON.stringify(newer)!==JSON.stringify(expected)){sharing=false;localLive=false;broadcast();publisher?.close().catch(()=>{});notice('Il tavolo è stato modificato in un’altra pagina. Ricarica per continuare.',true);}}else if(e.key==='glc_scontro_v1'&&selected)renderInspector();}catch(error){sharing=false;localLive=false;broadcast();publisher?.close().catch(()=>{});notice('Sessione non più disponibile. Torna al Profilo.',true);}});
 window.addEventListener('pagehide',()=>{dead=true;localLive=false;broadcast();channel?.close();clearInterval(heartbeat);clearTimeout(publishTimer);publisher?.close().catch(()=>{});board?.destroy();});
 init();
})();
