const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
function fixture(){const x={console};vm.createContext(x);for(const file of ['regole/prestigio-data.js','regole/prestigio.js','regole/talenti.js','regole/nave-talenti.js','regole/nave.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'..',file),'utf8'),x);return {x,G:x.GLCShip};}
const json=x=>JSON.parse(JSON.stringify(x));
test('empty new ship has safe skill and maneuver profiles without any crew',()=>{const {G}=fixture(),s=G.blank();assert.equal(G.skill(null,'Carpenteria'),'');for(const type of Object.keys(G.maneuvers)){const p=G.profile(s,type,{});assert.equal(p.valid,false,type);assert.ok(p.errors.some(e=>e.includes('operatore')),type);assert.ok(Array.isArray(p.dice));}assert.equal(G.occupant(s,'ingegnere',{}),null);});
function c(style,die='d12',talents=[]){const role=style==='Navigatore'?'Navigatore':'Ingegnere';return {nome:style,role,style,roleSkillDie:die,attr:{Forza:'d6',Tecnica:'d8',Astuzia:'d10',Spirito:'d4'},skills:{},talents:talents.map(n=>role+' · '+style+' · '+n)};}
function ready(G){const s=G.blank();s.crew.cannoniere={charId:'gun'};s.crew.timoniere={charId:'helm'};s.crew.capitano={charId:'capt'};s.crew.ingegnere={charId:'eng'};G.beginBattle(s);G.beginRound(s);return s;}
test('new ship matches manual, historical and unknown nested records stay unchanged',()=>{const {G}=fixture();assert.equal(G.blank().psCur,40);assert.equal(G.blank().stats.scafo,'d8');const raw={id:'old',stats:{scafo:'d6',vele:'d20',custom:9},psCur:23,crew:{capitano:{nome:'X',attr:'d12',note:'keep'}},distrutti:{timone:true,unknown:true},png:{lealta:7},moduli:[{id:'m',nome:'Custom',slot:1,private:{a:1}},null],photo:'photo',note:'note',custom:{keep:true}};const before=json(raw),s=G.normalize(raw);assert.deepEqual(raw,before);assert.equal(s.psCur,23);assert.equal(s.stats.scafo,'d6');assert.equal(s.stats.vele,'d20');assert.equal(s.stats.custom,9);assert.equal(s.crew.capitano.note,'keep');assert.equal(s.moduli[0].id,'m');assert.deepEqual(json(s.legacyModuleRecords),[null]);assert.deepEqual(json(G.normalize(s)),json(s));});
test('conditions are exact at thresholds; watertight survives 0 through -9 only',()=>{const {G}=fixture(),s=G.blank();for(const [ps,cond] of [[31,'INTEGRA'],[30,'DANNEGGIATA'],[20,'GRAVE'],[10,'CRITICA'],[0,'AFFONDATA']]){s.psCur=ps;assert.equal(G.condition(s),cond);}G.install(s,{nome:'Compartimenti stagni',slot:1});for(const ps of [0,-4,-9]){G.setPS(s,ps);assert.equal(G.condition(s),'CRITICA');}G.setPS(s,-10);assert.equal(G.condition(s),'AFFONDATA');});
test('hull damage clips only above new maximum and repair never restores current PS',()=>{const {G}=fixture(),s=G.blank();G.setComponent(s,'scafo',true);assert.equal(G.psMax(s),30);assert.equal(s.psCur,30);G.setComponent(s,'scafo',false);assert.equal(G.psMax(s),40);assert.equal(s.psCur,30);s.psCur=8;G.setComponent(s,'scafo',true);assert.equal(s.psCur,8);});
test('component penalty requires explicit GM choice and preserves original dice',()=>{const {G}=fixture(),s=ready(G),chars={helm:c('Navigatore'),gun:c('Meccanico')};G.setComponent(s,'albero',true);assert.equal(G.profile(s,'evasiva',chars).valid,false);s.penalitaComponenti='gradino';assert.deepEqual(json(G.profile(s,'evasiva',chars).dice),['d4','d10']);assert.equal(s.stats.vele,'d6');s.penalitaComponenti='dado';assert.deepEqual(json(G.profile(s,'evasiva',chars).dice),['d10']);G.setComponent(s,'albero',false);assert.deepEqual(json(G.profile(s,'evasiva',chars).dice),['d6','d10']);});
test('captain Strength is used for ramming, never Spirit fallback',()=>{const {G}=fixture(),s=ready(G);s.crew.capitano={nome:'Cap',attr:'d12'};assert.equal(G.profile(s,'speronamento',{}).valid,false);s.crew.capitano.attrs={Forza:'d6'};assert.deepEqual(json(G.profile(s,'speronamento',{}).dice),['d8','d6']);});
test('station references current pirate and detects missing or changed attribute',()=>{const {G}=fixture(),s=ready(G),chars={gun:c('Meccanico')};assert.deepEqual(json(G.profile(s,'cannonate',chars).dice),['d6','d8']);chars.gun.attr.Tecnica='d20+d20';assert.deepEqual(json(G.profile(s,'cannonate',chars).dice),['d6','d20+d20']);delete chars.gun;assert.equal(G.profile(s,'cannonate',chars).valid,false);});
test('navigation talent applies only to its own maneuver; invalid talent has no benefit',()=>{const {G}=fixture(),s=ready(G),chars={helm:c('Navigatore','d8',['Mano al Timone','Timoniere Nato — Base','Vento in Poppa'])};assert.deepEqual(json(G.profile(s,'traversata',chars).dice),['d6','d10','d8']);assert.deepEqual(json(G.profile(s,'evasiva',chars).dice),['d6','d10','d8']);assert.deepEqual(json(G.profile(s,'fuga',chars).dice),['d6','d10']);chars.helm.roleSkillDie='d6';assert.deepEqual(json(G.profile(s,'traversata',chars).dice),['d6','d10']);});
test('one maneuver and one operator action; Vento gives maneuver but never extra Action',()=>{const {G}=fixture(),s=ready(G),chars={helm:c('Navigatore','d10',['Vento in Poppa']),gun:c('Meccanico')};G.resolve(s,'evasiva',chars,{total:9});assert.throws(()=>G.resolve(s,'fuga',chars,{total:12}),/Azione/);G.resolve(s,'cannonate',chars,{total:9});assert.equal(s.battle.used.length,2);assert.throws(()=>G.resolve(s,'cannonate',chars,{total:9}),/Azione/);G.beginRound(s);assert.equal(s.battle.used.length,0);});
test('no role or PNG size grants an additional maneuver',()=>{const {G}=fixture(),s=ready(G),chars={helm:c('Navigatore'),gun:c('Meccanico')};s.png.dim='Esperto (21+)';G.resolve(s,'evasiva',chars,{total:9});const before=json(s);assert.throws(()=>G.resolve(s,'cannonate',chars,{total:9}),/Manovre/);assert.deepEqual(json(s),before);});
test('Maestria permits helm maneuver and shot from distinct Actions',()=>{const {G}=fixture(),s=ready(G),chars={helm:c('Navigatore','d12',['Timoniere Nato — Base','Timoniere Nato — Migliorato','Timoniere Nato — Maestria']),gun:c('Meccanico')};G.resolve(s,'evasiva',chars,{total:10});G.resolve(s,'cannonate',chars,{total:9});assert.equal(s.battle.used.length,2);});
test('cannon thresholds/range and damaged systems cannot be bypassed through resolve',()=>{const {G}=fixture(),s=ready(G),chars={gun:c('Meccanico'),helm:c('Navigatore')};assert.equal(G.profile(s,'cannonate',chars,{band:2}).threshold,12);const before=json(s);assert.throws(()=>G.resolve(s,'cannonate',chars,{total:50,band:3}),/portata/);assert.deepEqual(json(s),before);G.setComponent(s,'timone',true);assert.throws(()=>G.resolve(s,'evasiva',chars,{total:20}),/Timone/);G.setComponent(s,'macchine',true);assert.throws(()=>G.resolve(s,'fuga',chars,{total:20}),/macchine/);});
test('misusing twins is rejected atomically; available extra shot costs another action',()=>{const {G}=fixture(),s=ready(G),chars={helm:c('Navigatore'),gun:c('Meccanico')};const before=json(s);assert.throws(()=>G.resolve(s,'evasiva',chars,{total:9,gemelli:true}),/gemelli/);assert.deepEqual(json(s),before);});
test('ramming takes 1d4 recoil on failure and requires physical collision',()=>{const {G}=fixture(),s=ready(G),chars={capt:c('Meccanico')};assert.throws(()=>G.resolve(s,'speronamento',chars,{total:2,recoil:3,collision:false}),/collisione/);G.resolve(s,'speronamento',chars,{total:2,recoil:3,collision:true});assert.equal(s.psCur,37);});
test('emergency repair needs acquired ability/materials and signature multiplies actual heal',()=>{const {G}=fixture(),s=ready(G),chars={eng:c('Carpentiere','d10',["Riparazione d'Emergenza",'Mani sul Legno — Base'])};s.psCur=10;assert.equal(G.profile(s,'emergenza',chars).repairDice,2);assert.throws(()=>G.resolve(s,'emergenza',chars,{total:12,heal:8}),/materiali/);const r=G.resolve(s,'emergenza',chars,{total:12,heal:8,materials:true});assert.equal(r.heal,16);assert.equal(s.psCur,26);G.beginRound(s);chars.eng.talents=[];assert.throws(()=>G.resolve(s,'emergenza',chars,{total:12,heal:30,materials:true}),/acquisita/);});
test('pursuit tie leaves band, losing gives opportunity, winning gains one band',()=>{const {G}=fixture(),s=ready(G),chars={helm:c('Navigatore')};s.battle.band=1;const tie=G.resolve(s,'fuga',chars,{total:10,opponent:10,opposed:true});assert.equal(s.battle.band,1);assert.equal(tie.opportunity,false);G.beginRound(s);const loss=G.resolve(s,'fuga',chars,{total:9,opponent:10,opposed:true});assert.equal(loss.opportunity,true);G.beginRound(s);G.resolve(s,'fuga',chars,{total:11,opponent:10,opposed:true});assert.equal(s.battle.band,2);});
test('critical entry requests one component roll and second duplicate cannot reroll forever',()=>{const {G}=fixture(),s=ready(G);G.setPS(s,10);assert.equal(s.battle.criticalPending,true);G.componentRoll(s,1);assert.equal(s.battle.criticalPending,false);G.setPS(s,9);assert.equal(s.battle.criticalPending,false);G.setPS(s,20);G.setPS(s,10);assert.equal(s.battle.criticalPending,true);const r=G.componentRoll(s,1,1);assert.equal(r.gm,true);assert.throws(()=>G.componentRoll(s,2),/GM/);});
test('ship slots/cargo are separate; over-capacity historical data retained, new install blocked',()=>{const {G}=fixture(),s=G.blank();G.install(s,{nome:'Stiva ampliata',slot:1,parametri:{stiva:6}});assert.equal(G.capacity(s),18);assert.equal(G.slotsUsed(s),1);G.install(s,{nome:'Custom',slot:1});assert.throws(()=>G.install(s,{nome:'Neg',slot:-2}),/positivo/);assert.throws(()=>G.install(s,{nome:'Third',slot:1}),/Slot/);s.stats.struttura='d4';assert.equal(s.moduli.length,2);assert.ok(G.warnings(s).some(w=>w.includes('oltre capacità')));});
test('weekly provisions round separately and reductions apply before rounding',()=>{const {G}=fixture();assert.equal(G.provisions(6,2),4);assert.equal(G.provisions(10),2);assert.equal(G.provisions(11,2,.5),4);assert.throws(()=>G.provisions(6,1.5),/parziali/);});
test('persistent improvements belong to ship, total slots replace earlier upgrade',()=>{const {G}=fixture(),s=G.blank();s.miglioramenti.maestroDeiModuli=true;assert.equal(G.slotsTotal(s),3);s.miglioramenti.naveLeggendaria=1;assert.equal(G.slotsTotal(s),4);assert.equal(G.psMax(s),60);G.setComponent(s,'scafo',true);assert.equal(G.psMax(s),50);s.miglioramenti.naveLeggendaria=2;assert.equal(G.slotsTotal(s),5);assert.equal(G.psMax(s),70);});
test('Nave talent catalogue agrees with management, prevents drift',()=>{const {x}=fixture(),s=fs.readFileSync(path.join(__dirname,'../gestisci-pirata/index.html'),'utf8'),f={};vm.createContext(f);vm.runInContext(s.slice(s.indexOf('const TALENTS='),s.indexOf('const TAL_RITIRATI='))+';this.catalog=TALENTS;',f);for(const role of Object.keys(x.GLCShipTalents))assert.deepEqual(json(x.GLCShipTalents[role]),json(f.catalog[role]));});
