#!/usr/bin/env python3
"""Rebuild the Prestige manual and shared UI descriptions from checked-in sources.
The four DOCX inputs were extracted in order into regole/prestigio-fonti.json.
Only explicit editorial revisions in prestigio-revisioni.json may change wording.
"""
from pathlib import Path
import json,re,html,unicodedata
ROOT=Path(__file__).resolve().parent.parent
sources=json.loads((ROOT/'regole/prestigio-fonti.json').read_text())
revisioni=json.loads((ROOT/'regole/prestigio-revisioni.json').read_text())
for edit in revisioni:
 if 'blocchi' in edit or 'escludi_capitolo' in edit:continue
 b=sources[edit['source']][edit['block']]
 if 'togli_riga' in edit:
  assert b['type']=='table',edit
  prima=len(b['rows']);b['rows']=[r for r in b['rows'] if r[0]!=edit['togli_riga']]
  assert len(b['rows'])==prima-edit.get('quante',1),edit
  continue
 if b['type']=='table':
  assert any(edit['from'] in v for row in b['rows'] for v in row),edit
  b['rows']=[[v.replace(edit['from'],edit['to']) for v in row] for row in b['rows']]
  continue
 assert edit['from'] in b['text'];b['text']=b['text'].replace(edit['from'],edit['to'])
# Editorial additions: new blocks spliced after an existing one. The DOCX sources
# stay untouched; every fixed index below is translated through shift(), so the
# chapter ranges and the talent spans keep pointing at the same text.
aggiunte=[e for e in revisioni if 'blocchi' in e]
for e in sorted(aggiunte,key=lambda e:-e['after']):
 blocchi=[dict(type='table',rows=x['rows'],aggiunta=True) if x.get('type')=='table' else dict(type='p',style=x.get('style','Normal'),text=x['text'],aggiunta=True) for x in e['blocchi']]
 sources[e['source']][e['after']+1:e['after']+1]=blocchi
def shift(src,i):
 return i+sum(len(e['blocchi']) for e in aggiunte if e['source']==src and e['after']+1<=i)
def slug(s):return re.sub(r'[^a-z0-9]+','-',unicodedata.normalize('NFKD',s).encode('ascii','ignore').decode().lower()).strip('-')
def section(src,name):
 blocks=sources[src];start=next(i for i,b in enumerate(blocks) if b.get('text')==name and b.get('style','').startswith('Heading'))
 level=int(blocks[start]['style'][-1]);end=next((i for i in range(start+1,len(blocks)) if blocks[i].get('style','').startswith('Heading') and int(blocks[i]['style'][-1])<=level),len(blocks))
 return dict(source=src,start=start,end=end,anchor=src+'-'+slug(name),blocks=blocks[start+1:end])
data=json.loads((ROOT/'regole/prestigio-catalogo.json').read_text())
for t in data['talents']+data['haki']:
 t['start'],t['end']=shift(t['source'],t['start']),shift(t['source'],t['end'])
 t['blocks']=sources[t['source']][t['start']+1:t['end']]
data['attributes']={k:section('combattenti',n) for k,n in [('Forza','Prestigio di Forza'),('Tecnica','Prestigio di Tecnica'),('Astuzia','Prestigio di Astuzia'),('Lama','Scale di Forza e Tecnica per lo Swordsman')]}
data['attributes']['Spirito']=section('haki','Prestigio di Spirito')
(ROOT/'regole/prestigio-data.js').write_text('/* Generated by strumenti/prestigio-manuale.py. */\n(function(root){root.GLCPrestigeData='+json.dumps(data,ensure_ascii=False,separators=(',',':'))+';})(typeof window!=="undefined"?window:globalThis);\n')
esc=html.escape
chapters=[(s_,shift(s_,a),shift(s_,b),t_) for s_,a,b,t_ in
 [('introduzione',2,27,'Entrare nel Prestigio'),('combattenti',3,141,'Il Prestigio degli Attributi'),('combattenti',141,323,'I Talenti del Combattente'),('combattenti',323,371,'Combinazioni e risoluzione al tavolo'),('ruoli',3,25,'Il Prestigio delle Skill di Ruolo')]]
starts=[25,43,62,81,101,123,144,167,189,208,230,248]
for a,b in zip(starts,starts[1:]+[252]):chapters.append(('ruoli',shift('ruoli',a),shift('ruoli',b),sources['ruoli'][shift('ruoli',a)]['text']))
for a,b,title in [(3,35,'Spirito e Haki regole comuni'),(35,57,'Il Prestigio di Spirito'),(57,89,'Il Prestigio di Armamento'),(89,113,'Il Prestigio di Osservazione'),(113,143,'Il Prestigio del Re'),(143,167,'Haki e Spirito al tavolo')]:chapters.append(('haki',shift('haki',a),shift('haki',b),title))
# Capitoli tolti dal manuale con una revisione: si indicano con gli indici
# originali delle fonti, tradotti da shift() come tutti gli altri.
esclusi=set()
for e in revisioni:
 if 'escludi_capitolo' not in e:continue
 a,b=e['escludi_capitolo'];a,b=shift(e['source'],a),shift(e['source'],b)
 prima=len(chapters);chapters=[c for c in chapters if not (c[0]==e['source'] and c[1]==a and c[2]==b)]
 assert len(chapters)==prima-1,e
 esclusi|={(e['source'],i) for i in range(a,b)}
# Use the base manual's actual presentation template without executing its DOCX
# generator. Its controls, reading layout and navigation script remain the single
# reference for both manuals; only this manual's palette is overridden.
import ast
from html.parser import HTMLParser
base_generator=(ROOT/'strumenti/manuale-da-docx.py').read_text()
base_template=next(ast.literal_eval(n.value) for n in ast.parse(base_generator).body
                   if isinstance(n,ast.Assign) and any(isinstance(t,ast.Name) and t.id=='PAGINA' for t in n.targets))
shell_start=base_template.index('<header class="man-top">')
shell_end=base_template.index('\n<script>',shell_start)
shell=base_template[shell_start:shell_end]
reader_start=base_template.index('<script>',shell_end)+len('<script>')
reader_end=base_template.index('</script>',reader_start)
reader=base_template[reader_start:reader_end].strip()
assert 'var indice=document.getElementById("man-indice")' in reader
assert 'solo lettura.' in reader

anchors=set();rendered=[];toc=[];summary=[];included=set()
def anchor(src,i,b):
 a=src+'-'+slug(b['text'])
 if a in anchors:a+='-'+str(i)
 anchors.add(a);return a

def source_attr(src,i):return f' data-prestigio-source="{src}:{i}"'

def block_html(src,i,b,number=None):
 provenance=source_attr(src,i)
 if b['type']=='table':
  return '<div class="man-tab-wrap" tabindex="0" role="region" aria-label="Tabella delle regole"'+provenance+'><table class="man-tab"><thead><tr>'+''.join('<th scope="col">'+esc(v)+'</th>' for v in b['rows'][0])+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+esc(v).replace('\n','<br>')+'</td>' for v in row)+'</tr>' for row in b['rows'][1:])+'</tbody></table></div>'
 txt=b['text'];style=b['style']
 if style.startswith('Heading'):
  a=anchor(src,i,b)
  if style in ['Heading 1','Heading 2']:
   return f'<h2 class="man-sez" id="{a}"><span class="man-sez-n">{number}</span><span{provenance}>{esc(txt)}</span></h2>'
  level=3 if style=='Heading 3' else 4
  cls='man-sub' if level==3 else 'man-lab'
  return f'<h{level} class="{cls}" id="{a}"{provenance}>{esc(txt)}</h{level}>'
 return '<p'+provenance+'>'+esc(txt)+'</p>'

for no,(src,start,end,title) in enumerate(chapters,1):
 content=[];links=[];chapter_anchor='';section_number=0;chapter_source='';i=start
 while i<end:
  b=sources[src][i];included.add((src,i))
  if i==start and b.get('text')==title and b.get('style','').startswith('Heading'):
   chapter_anchor=anchor(src,i,b);chapter_source=source_attr(src,i);i+=1;continue
  if b.get('style') in ['Heading 1','Heading 2']:
   section_number+=1;number=f'{no}.{section_number}'
   content.append(block_html(src,i,b,number))
   a=src+'-'+slug(b['text'])
   if a+'-'+str(i) in anchors:a+='-'+str(i)
   links.append(f'<li><a href="#{a}" data-id="{a}">{number} · {esc(b["text"])}</a></li>')
   summary.append(('section',no,number,b['text']))
  elif b.get('style') in ['List Bullet','List Number']:
   style=b['style'];tag='ul' if style=='List Bullet' else 'ol';cls='man-punti' if tag=='ul' else 'man-passi'
   items=[]
   while i<end and sources[src][i].get('style')==style:
    included.add((src,i));items.append('<li'+source_attr(src,i)+'>'+esc(sources[src][i]['text'])+'</li>');i+=1
   content.append(f'<{tag} class="{cls}">'+''.join(items)+f'</{tag}>');continue
  else:content.append(block_html(src,i,b))
  i+=1
 rendered.append(f'<section class="man-cap" id="cap-{no}" aria-labelledby="titolo-{no}"><header class="man-cap-h" id="{chapter_anchor or "cap-intro-"+str(no)}"><span class="man-cap-n">Capitolo {no:02}</span><h1 id="titolo-{no}"{chapter_source}>{esc(title)}</h1></header><div class="man-cap-corpo">'+''.join(content)+'</div></section>')
 toc.append(f'<li class="man-i-cap"><a href="#cap-{no}" data-id="cap-{no}"><span class="n">{no}</span>{esc(title)}</a>'+('<ol class="man-i-sez">'+''.join(links)+'</ol>' if links else '')+'</li>')
expected={(s,i) for s,blocks in sources.items() for i,b in enumerate(blocks) if b.get('style') not in ['Title','Subtitle']}
expected-=esclusi
assert included==expected,(expected-included,included-expected)

# The printed table of contents follows the same structure as the base manual.
somm=[]
for no,(_,_,_,title) in enumerate(chapters,1):
 somm.append(f'<li class="s-cap">{no} · {esc(title)}</li>')
 somm.extend('<li class="s-sez"><b>'+number+'</b>'+esc(text)+'</li>' for _,chapter,number,text in summary if chapter==no)
shell=shell.replace('\nNAV\n','\n'+'\n'.join(toc)+'\n').replace('\nSOMM\n','\n'+'\n'.join(somm)+'\n').replace('\nCORPO\n','\n'+'\n'.join(rendered)+'\n')
# Preserve the old public content anchor as well as every chapter/section anchor.
shell=shell.replace('<main class="man-foglio" id="man-foglio">','<main class="man-foglio" id="man-foglio"><span id="contenuto" aria-hidden="true"></span>')
shell=shell.replace('Manuale<br>del gioco','Manuale<br>del Prestigio').replace('Edizione 2.0 · dalla creazione del pirata alla rotta della ciurma.','Espansione ufficiale · Attributi, Talenti di Ruolo, Spirito e Haki, oltre il d20 fino a Saikyō.')
editorial='Le evoluzioni dei Talenti di Ruolo sostituiscono le versioni precedenti come scelte utilizzabili. I prerequisiti acquisiti e i benefici incorporati restano validi. Gli effetti Haki conservano invece le alternative base espressamente previste.'
shell=shell.replace('    <nav class="man-somm"', '    <p class="man-guida">'+editorial+'</p>\n\n    <nav class="man-somm"')

# Reuse the base manual's fonts and layout asset; Prestige supplies only its palette.
base_head=base_template[:base_template.index('<style>')]
base_head=base_head.replace('<title>Manuale · Grand Line Chronicles</title>','<title>Manuale del Prestigio · Grand Line Chronicles</title>')
base_head=re.sub(r'<meta name="description"[^>]+>', '<meta name="description" content="Il manuale ufficiale del Prestigio: Attributi, Talenti di Ruolo, Spirito, Haki e Saikyō.">',base_head)
base_head=base_head.replace('href="manuale.css?', 'href="/manuale/manuale.css?')
head=base_head+'<link rel="stylesheet" href="prestigio.css?v=2">\n<script src="reader.js?v=2" defer></script>\n</head>\n<body class="manuale-prestigio">\n<div class="glc-bg" aria-hidden="true"></div>\n'
out=head+shell+'\n</body>\n</html>\n'

# Exact normative-text check, independent of the heading/list/table markup.
class SourceText(HTMLParser):
 def __init__(self):super().__init__();self.level=0;self.active=None;self.texts={}
 def handle_starttag(self,tag,attrs):
  attrs=dict(attrs)
  if tag in ['br','img','input','link','meta','hr','source','wbr']:
   if self.active:self.texts[self.active[0]].append(' ')
   return
  self.level+=1
  if 'data-prestigio-source' in attrs:
   key=attrs['data-prestigio-source'];assert key not in self.texts,key
   self.active=(key,self.level);self.texts[key]=[]
 def handle_endtag(self,tag):
  if self.active:
   if self.level==self.active[1]:self.active=None
   else:self.texts[self.active[0]].append(' ')
  self.level-=1
 def handle_data(self,text):
  if self.active:self.texts[self.active[0]].append(text)
def norm(text):return re.sub(r'\s+',' ',unicodedata.normalize('NFC',text)).strip()
parsed=SourceText();parsed.feed(out)
assert len(parsed.texts)==len(expected)
for src,i in expected:
 b=sources[src][i];original=b['text'] if b['type']=='p' else ' '.join(cell for row in b['rows'] for cell in row)
 assert norm(''.join(parsed.texts[f'{src}:{i}']))==norm(original),f'Text mismatch: {src}:{i}'
target=ROOT/'manuale-prestigio';target.mkdir(exist_ok=True)
(target/'index.html').write_text(out)
(target/'reader.js').write_text('/* Generated from the base manual UI by strumenti/prestigio-manuale.py. */\n'+reader+'\n')
print(f'Manuale del Prestigio: {len(chapters)} capitoli, {len(anchors)} sezioni, {len(included)} blocchi. Copertura e testo integrale delle quattro fonti: True. UI: Manuale base.')
