#!/usr/bin/env python3
"""Rebuild the Prestige manual and shared UI descriptions from checked-in sources.
The four DOCX inputs were extracted in order into regole/prestigio-fonti.json.
Only explicit editorial revisions in prestigio-revisioni.json may change wording.
"""
from pathlib import Path
import json,re,html,unicodedata
ROOT=Path(__file__).resolve().parent.parent
sources=json.loads((ROOT/'regole/prestigio-fonti.json').read_text())
for edit in json.loads((ROOT/'regole/prestigio-revisioni.json').read_text()):
 b=sources[edit['source']][edit['block']];assert edit['from'] in b['text'];b['text']=b['text'].replace(edit['from'],edit['to'])
def slug(s):return re.sub(r'[^a-z0-9]+','-',unicodedata.normalize('NFKD',s).encode('ascii','ignore').decode().lower()).strip('-')
def section(src,name):
 blocks=sources[src];start=next(i for i,b in enumerate(blocks) if b.get('text')==name and b.get('style','').startswith('Heading'))
 level=int(blocks[start]['style'][-1]);end=next((i for i in range(start+1,len(blocks)) if blocks[i].get('style','').startswith('Heading') and int(blocks[i]['style'][-1])<=level),len(blocks))
 return dict(source=src,start=start,end=end,anchor=src+'-'+slug(name),blocks=blocks[start+1:end])
data=json.loads((ROOT/'regole/prestigio-catalogo.json').read_text())
for t in data['talents']+data['haki']:t['blocks']=sources[t['source']][t['start']+1:t['end']]
data['attributes']={k:section('combattenti',n) for k,n in [('Forza','Prestigio di Forza'),('Tecnica','Prestigio di Tecnica'),('Astuzia','Prestigio di Astuzia'),('Lama','Scale di Forza e Tecnica per lo Swordsman')]}
data['attributes']['Spirito']=section('haki','Prestigio di Spirito')
(ROOT/'regole/prestigio-data.js').write_text('/* Generated by strumenti/prestigio-manuale.py. */\n(function(root){root.GLCPrestigeData='+json.dumps(data,ensure_ascii=False,separators=(',',':'))+';})(typeof window!=="undefined"?window:globalThis);\n')
esc=html.escape
chapters=[('introduzione',2,27,'Entrare nel Prestigio'),('combattenti',3,141,'Il Prestigio degli Attributi'),('combattenti',141,323,'I Talenti del Combattente'),('combattenti',323,371,'Combinazioni e risoluzione al tavolo'),('ruoli',3,25,'Il Prestigio delle Skill di Ruolo')]
starts=[25,43,62,81,101,123,144,167,189,208,230,248]
for a,b in zip(starts,starts[1:]+[252]):chapters.append(('ruoli',a,b,sources['ruoli'][a]['text']))
for a,b,title in [(3,35,'Spirito e Haki regole comuni'),(35,57,'Il Prestigio di Spirito'),(57,89,'Il Prestigio di Armamento'),(89,113,'Il Prestigio di Osservazione'),(113,143,'Il Prestigio del Re'),(143,167,'Haki e Spirito al tavolo')]:chapters.append(('haki',a,b,title))
anchors=set();rendered=[];toc=[];included=set()
def block_html(src,i,b):
 if b['type']=='table':
  return '<div class="pr-table-scroll" tabindex="0" role="region" aria-label="Tabella delle regole"><table><thead><tr>'+''.join('<th scope="col">'+esc(v)+'</th>' for v in b['rows'][0])+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+esc(v).replace('\n','<br>')+'</td>' for v in row)+'</tr>' for row in b['rows'][1:])+'</tbody></table></div>'
 txt=b['text'];style=b['style']
 if style.startswith('Heading'):
  a=src+'-'+slug(txt)
  if a in anchors:a+='-'+str(i)
  anchors.add(a);level=min(6,int(style[-1])+2)
  return f'<h{level} id="{a}">{esc(txt)}</h{level}>'
 return '<p'+(' class="pr-bullet"' if style=='List Bullet' else ' class="pr-step"' if style=='List Number' else '')+'>'+esc(txt)+'</p>'
for no,(src,start,end,title) in enumerate(chapters,1):
 content=[];links=[];chapter_anchor=""
 for i in range(start,end):
  b=sources[src][i];included.add((src,i))
  if i==start and b.get('text')==title and b.get('style','').startswith('Heading'):
   chapter_anchor=src+'-'+slug(title);anchors.add(chapter_anchor)
  else:content.append(block_html(src,i,b))
  if b.get('style') in ['Heading 1','Heading 2']:
   a=src+'-'+slug(b['text']);links.append('<a href="#'+a+'">'+esc(b['text'])+'</a>')
 rendered.append(f'<section class="pr-chapter" id="cap-{no}" aria-labelledby="titolo-{no}"><header id="{chapter_anchor or "cap-intro-"+str(no)}"><span>CAPITOLO {no:02}</span><h2 id="titolo-{no}">{esc(title)}</h2></header>'+''.join(content)+'</section>')
 toc.append(f'<details><summary><a href="#cap-{no}"><span>{no:02}</span> {esc(title)}</a></summary>'+''.join(links)+'</details>')
expected={(s,i) for s,blocks in sources.items() for i,b in enumerate(blocks) if b.get('style') not in ['Title','Subtitle']}
assert included==expected,(expected-included,included-expected)
head='''<!doctype html><html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Manuale del Prestigio · Grand Line Chronicles</title><meta name="description" content="Il manuale ufficiale del Prestigio: Attributi, Talenti di Ruolo, Spirito, Haki e Saikyō."><link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@500;600;700&family=Cormorant+Garamond:wght@400;500;600;700&family=Manrope:wght@400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="/manuali/manuali.css?v=1"><script src="reader.js?v=1" defer></script></head><body class="pr-reader"><a class="pr-skip" href="#contenuto">Vai al manuale</a><header class="pr-top"><a class="pr-brand" href="/grand-line-chronicles/">⚓ <span>Grand Line Chronicles</span></a><nav><a href="/manuali/">Biblioteca</a><button id="pr-toc-toggle" aria-expanded="false" aria-controls="pr-index">Indice ☰</button><button id="pr-print">Stampa</button></nav></header><div class="pr-progress" aria-hidden="true"><i></i></div><aside class="pr-index" id="pr-index" aria-label="Indice del Manuale del Prestigio"><p class="pr-kicker">Manuale del Prestigio</p><label for="pr-search">Cerca nell’indice</label><input id="pr-search" type="search" placeholder="Talento, Haki, Attributo…"><nav>'''
cover='''</nav><p id="pr-empty" hidden>Nessuna sezione trovata.</p></aside><main id="contenuto" class="pr-reading"><header class="pr-cover"><p class="pr-kicker">Grand Line Chronicles · Espansione ufficiale</p><div class="pr-seal" aria-hidden="true">✦</div><h1>Manuale<br>del <em>Prestigio</em></h1><p>Attributi, Talenti di Ruolo, Spirito e Haki.<br>Le regole della crescita oltre il d20, fino a Saikyō.</p><div class="pr-cover-dice">d20 + d4 <span>→</span> d20 + d20</div><a class="pr-primary" href="#cap-1">Inizia la lettura ↓</a></header><p class="pr-editorial">Le evoluzioni dei Talenti di Ruolo sostituiscono le versioni precedenti come scelte utilizzabili. I prerequisiti acquisiti e i benefici incorporati restano validi. Gli effetti Haki conservano invece le alternative base espressamente previste.</p>'''
out=head+''.join(toc)+cover+''.join(rendered)+'''<footer class="pr-end"><p class="pr-kicker">Grand Line Chronicles</p><h2>La leggenda continua.</h2><a class="pr-primary" href="/gestisci-pirata/">Apri la scheda del pirata ↗</a><a href="/manuali/">Torna alla biblioteca</a></footer></main></body></html>'''
target=ROOT/'manuale-prestigio';target.mkdir(exist_ok=True);(target/'index.html').write_text(out)
print(f'Manuale del Prestigio: {len(chapters)} capitoli, {len(anchors)} sezioni, {len(included)} blocchi. Copertura integrale delle quattro fonti: True.')
