/* Deliberately independent of glc-auth/glc-sync: spectators never load private save archives. */
(function(){'use strict';const T=GLCTactical,host=document.getElementById('battle-board'),waiting=document.getElementById('waiting'),status=document.getElementById('connection'),login=document.getElementById('login');
 const board=GLCTacticalBoard.mount(host,{readOnly:true});let last=0,channel=null,reader=null,deadline=null,sb=null,authTicket=0;
 function scene(p){p=T.cleanPublic(p);waiting.hidden=!!p;board.render(p);document.getElementById('scene-title').textContent=p?.name||'Il campo di battaglia';}
 document.getElementById('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();board.fit();}catch(e){status.textContent='Schermo intero non disponibile in questo browser.';}};
 const local=new URLSearchParams(location.hash.slice(1)).get('local'),room=new URLSearchParams(location.search).get('room'),campaign=new URLSearchParams(location.search).get('campaign');
 if(local&&/^[a-f0-9-]{36}$/.test(local)){
  if(!window.BroadcastChannel){status.textContent='Usa un browser aggiornato per il secondo schermo.';return;}
  channel=new BroadcastChannel('glc-battle-'+local);channel.onmessage=e=>{if(e.data?.kind==='scene'){last=Date.now();scene(e.data.scene);status.textContent=e.data.scene?'Vista giocatori · secondo schermo':'Il GM ha sospeso la scena.';}};channel.postMessage({kind:'hello'});
  deadline=setInterval(()=>{if(Date.now()-last>15000){scene(null);status.textContent='In attesa del collegamento con il GM.';channel.postMessage({kind:'hello'});}},3000);
 }else if((room&&/^[a-f0-9-]{36}$/.test(room))||(campaign&&/^[a-f0-9-]{36}$/.test(campaign))){
  sb=window.__glcViewerSB||window.supabase?.createClient("https://anzxglqwmqbsthpqnxhc.supabase.co","eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFuenhnbHF3bXFic3RocHFueGhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODIxNDU2MDAsImV4cCI6MjA5NzcyMTYwMH0.aCPTlWmNapvU17ZwedkkhNztMG4PuskpZx3D9EfunIU");
  async function start(){const ticket=++authTicket;reader?.close();if(!sb){status.textContent='Servizio non disponibile. Ricarica la pagina.';return;}try{const r=await sb.auth.getUser();if(ticket!==authTicket)return;if(r.error||!r.data?.user){scene(null);waiting.textContent='Accedi per vedere il tavolo della tua campagna.';login.hidden=false;status.textContent='Accesso riservato alla ciurma.';return;}login.hidden=true;waiting.textContent='In attesa della scena del GM.';if(!room){const result=await sb.from('tactical_rooms').select('id,payload,expires_at').eq('campaign_id',campaign).eq('active',true);if(result.error)throw result.error;const rooms=(result.data||[]).filter(x=>Date.parse(x.expires_at)>Date.now());waiting.replaceChildren();const list=document.createElement('div');list.className='tb-picker';list.textContent=rooms.length?'Scegli il tavolo in scena':'Il GM non sta mostrando un tavolo.';for(const r of rooms){const a=document.createElement('a');a.className='tb-action';a.href='/campo-di-battaglia/?room='+encodeURIComponent(r.id);a.textContent=r.payload?.name||'Campo di battaglia';list.append(a);}const refresh=document.createElement('button');refresh.textContent='Aggiorna';refresh.onclick=start;list.append(refresh);waiting.append(list);status.textContent='Tavoli della campagna';return;}reader=GLCTacticalShare.reader(sb,room,scene,t=>status.textContent=t);}catch(e){scene(null);status.textContent='Accesso non verificabile. Riprova.';}}
  document.getElementById('retry').onclick=start;sb?.auth.onAuthStateChange(()=>{setTimeout(start,0);});start();
 }else{status.textContent='Apri il collegamento condiviso dal tuo GM.';}
 window.addEventListener('pagehide',()=>{reader?.close();channel?.close();clearInterval(deadline);board.destroy();});
})();