/* Official Fruit dossiers. Records are descriptive permissions, never free
 * Technique effects. All reads preserve the character and unknown fields. */
(function(root){
 'use strict';
 const dice=['d4','d6','d8','d10','d12','d20'],types=['Paramecia','Logia','Zoan'];
 const identity=[['nucleo','Nucleo del Potere'],['materia','Materia / Fenomeno / Creatura'],['applicazioni','Applicazioni iniziali'],['origine','Origine del potere'],['bersagli','Bersagli validi'],['portata','Portata ordinaria'],['quantita','Quantità ordinaria'],['durata','Durata ordinaria'],['precisione','Precisione del controllo'],['viventi','Interazione con esseri viventi'],['permanenza','Permanenza'],['limitazioni','Limitazioni strutturali'],['contraccolpi','Contraccolpi naturali']];
 const creature=[['specie','Specie'],['stazza','Stazza Bestiale'],['anatomia','Anatomia'],['movimento','Modalità di movimento'],['sensi','Sensi caratteristici'],['capacita','Capacità naturali'],['retaggio','Retaggio']];
 const combat=[['nome','Nome della Forma'],['manifestazione','Manifestazione'],['beneficio','Beneficio'],['costoAttivazione','Costo di attivazione'],['mantenimento','Costo di mantenimento'],['durata','Durata'],['limitazioni','Limitazioni della Forma']];
 const awakening=[['nome','Nome del Risveglio'],['principio','Principio Risvegliato'],['manifestazione','Manifestazione del Risveglio'],['benefici','Benefici concordati'],['area','Area / Portata'],['bersagli','Bersagli validi del Risveglio'],['viventi','Creature viventi nel Risveglio'],['permanenza','Permanenza del Risveglio'],['limitiSuperati','Limiti superati'],['limitiMantenuti','Limiti mantenuti'],['prezzo','Prezzo del Risveglio']];
 const families=['Origine','Costi / Sconti','Espansione','Dominio','Difesa','Attacco','Controllo'];
 const movement=['Scattatore terrestre','Massiccio terrestre','Arrampicatore','Volatore','Scavatore','Serpentino'];
 const sizes=['Piccola / Media','Grande','Enorme','Gigantesca','Colossale'];
 const weaponTypes=['Lama','Contundente','Ad asta','A distanza','Da lancio','Speciale'];
 const forms=['Umana','Ibrida','Bestiale'];
 const choices={Paramecia:[['glc-talent-224','Potere Versatile','Nuova Applicazione'],['glc-talent-226','Dono Passivo','Proprietà permanente'],['glc-talent-236','Seconda Natura','Nuova famiglia di Applicazioni']],Logia:[],Zoan:[['glc-talent-256','Sensi Animali','Sensi scelti'],['glc-talent-261','Retaggio Ancestrale','Capacità sbloccata'],['glc-talent-266','Retaggio Mitologico','Capacità sbloccata']]};
 const rules={
  Paramecia:{tratto:'Il Potere Unico · Sempre attivo. Il Nucleo e le Applicazioni concordate definiscono ciò che il Frutto può fare; i vantaggi meccanici richiedono Tecniche, Talenti o benefici espliciti.',firma:'L’impronta del potere · Colpo pulito +4 con una Tecnica del Frutto. Conseguenza coerente concordata col GM; gli Stati della Firma usano il Dado del Frutto per la Salvezza, gli effetti della Tecnica il Grado della Tecnica.'},
  Logia:{tratto:'L’Elemento · Sempre attivo. La natura elementale non costa ST né slot. Gli attacchi senza Haki o Pietra di Mare possono mancare o infliggere metà danno secondo natura e situazione decise dal GM. L’Haki non cancella indiscriminatamente il potere.',firma:'L’elemento dilaga · Colpo pulito +4 usando il Frutto. L’elemento si espande in una zona coerente; la Firma non assegna dimensioni o costi numerici universali.'},
  Zoan:{tratto:'Le Tre Forme · Umana, Ibrida e Bestiale. Cambio normale: Azione principale, 0 ST, nessuna Tecnica o slot. L’anatomia appropriata concede possibilità narrative; i bonus numerici dipendono dai Talenti.',firma:'Il Colpo Travolge · Colpo pulito +4 in Forma Ibrida: scegli Stordito (Salvezza di Forza dalla Soglia del Dado del Frutto) oppure +1 Dado Danno, mai entrambi.'}
 };
 const list=x=>Array.isArray(x)?x:[],text=x=>x==null?'':typeof x==='string'?x:JSON.stringify(x),present=x=>text(x).trim()!=='';
 function has(c,name){if(root.GLCTalents)return root.GLCTalents.has(c,name,{includeInherited:true});const f=read(c),min={'Artigli e Zanne':'d4','Potere Versatile':'d4','Dono Passivo':'d4','Corsa Bestiale':'d8','Stazza':'d8','Sensi Animali':'d8','Forma di Combattimento':'d12','Seconda Natura':'d12','Retaggio Ancestrale':'d12','Retaggio Mitologico':'d12','Risveglio':'d20'}[name];const branch={Zoan:['Artigli e Zanne','Corsa Bestiale','Stazza','Sensi Animali','Retaggio Ancestrale','Retaggio Mitologico'],Paramecia:['Potere Versatile','Dono Passivo','Forma di Combattimento','Seconda Natura']};if(!min||!f.has||!dice.includes(f.die)||(name!=='Risveglio'&&!list(branch[f.tipo]).includes(name))||!list(c.talents).includes('Frutto · '+f.tipo+' · '+name)||dice.indexOf(f.die)<dice.indexOf(min))return false;if(name==='Seconda Natura'&&!has(c,'Potere Versatile'))return false;if(name==='Retaggio Ancestrale'&&nature(f)!=='Ancestrale'||name==='Retaggio Mitologico'&&nature(f)!=='Mitologico')return false;if(name==='Risveglio'&&awakeningProblems(c).length)return false;return true;}
 function nature(f){return f.zoanType||f.subtipo||f.tipoZoan||'';}
 function read(c){return c.frutto||{};}
 function fields(f,key,schema){const data=f[key]&&typeof f[key]==='object'?f[key]:{};return schema.map(([k,label])=>({key:k,label,value:text(data[k])}));}
 function missing(c){const f=read(c);if(!f.has)return [];let out=[];
  if(!present(f.nome))out.push('Nome');if(!types.includes(f.tipo))out.push('Tipo');if(!dice.includes(f.die))out.push('Dado del Frutto');
  fields(f,'identita',identity).filter(x=>!present(x.value)).forEach(x=>out.push(x.label));
  if(f.tipo==='Zoan'){if(!['Ordinario','Ancestrale','Mitologico'].includes(nature(f)))out.push('Categoria Zoan');fields(f,'creatura',creature).filter(x=>!present(x.value)&&!(x.key==='retaggio'&&nature(f)==='Ordinario')).forEach(x=>out.push(x.label));}
  return out;
 }
 function naturalWeapons(c,options={}){const f=read(c),usable=f.has&&f.tipo==='Zoan'&&has(c,'Artigli e Zanne');return list(f.armiNaturali).map(w=>{
  const errors=[],add=t=>errors.push(t);if(!w||typeof w!=='object')return {raw:w,valid:false,errors:['Scheda dell’Arma Naturale da correggere.']};
  if(!usable)add('Richiede uno Zoan posseduto e Artigli e Zanne acquisito e sbloccato.');
  if(!present(w.id))add('Manca l’ID dell’Arma Naturale.');else if(list(f.armiNaturali).filter(a=>a&&a.id===w.id).length>1)add('L’ID dell’Arma Naturale è duplicato: correggi il record conservato.');if(!present(w.nome))add('Manca il nome dell’Arma Naturale.');if(!present(w.anatomia))add('Registra la parte anatomica.');
  if(!weaponTypes.includes(w.tipo))add('Registra un normale tipo d’arma.');if(!['Forza','Tecnica'].includes(w.attr))add('Registra l’Attributo dell’arma: Forza o Tecnica.');
  if(w.tipo==='Ad asta'&&!['Tagliente','Contundente'].includes(w.asta))add('Registra la modalità dell’asta.');
  const allowed=list(w.forme);if(!allowed.length||allowed.some(x=>!forms.includes(x)))add('Registra le forme nelle quali l’anatomia è disponibile.');
  if(!present(w.portata))add('Registra la Portata concordata.');if(!dice.includes(f.die))add('Il Dado del Frutto deve essere da d4 a d20.');
  const operationalErrors=[];const attributeDie=c.attr?.[w.attr]||'',attributeRank=/^d20\+d(?:4|6|8|10|12|20)$/.test(attributeDie)?5:dice.indexOf(attributeDie);if(options.purpose==='use'&&dice.includes(f.die)&&attributeRank<dice.indexOf(f.die))operationalErrors.push('L’Arma Naturale richiede '+w.attr+' almeno '+f.die+'; il Grado resta il Dado del Frutto, senza riduzione automatica.');if(options.purpose==='use'&&!allowed.includes(f.forma))operationalErrors.push('L’Arma Naturale non è disponibile nella forma attuale registrata ('+(f.forma||'da registrare')+').');
  if(options.purpose==='use'&&f.esaurito)operationalErrors.push('Frutto / trasformazioni indisponibili fino al prossimo Riposo Lungo.');
  const weapon={...w,id:'natural:'+w.id,rawId:w.id,natural:true,grado:f.die||'',portata:text(w.portata),nome:w.nome||'Arma Naturale',eff:null};
  const sizeReach=f.forma==='Bestiale'&&has(c,'Stazza')?[1,2,3,4,5][sizes.indexOf(f.creatura?.stazza)]:null;const reach=sizeReach&&['Lama','Contundente','Ad asta','Speciale'].includes(w.tipo)?'Stazza in Forma Bestiale: Portata in mischia = maggiore fra '+text(w.portata)+' e '+sizeReach+' m. Nessun aumento in Ibrida.':'';
  return {...weapon,reach,raw:w,valid:errors.length===0,operational:errors.length===0&&operationalErrors.length===0,errors,operationalErrors};
 });}
 function arsenal(c,options={}){return list(c.armi).concat(naturalWeapons(c,options).filter(w=>w.valid));}
 function naturalAttack(c,id){const w=naturalWeapons(c,{purpose:'use'}).find(w=>w.id===id||w.rawId===id);if(!w)return null;const problems=w.errors.concat(w.operationalErrors||[]);const use=root.GLCTechniques?.weaponUseError(c,w);if(use)problems.push(use);const f=read(c),signature=f.forma==='Ibrida'?'Firma Zoan · Quando questo attacco base ottiene un colpo pulito +4 in Forma Ibrida, scegli Stordito (Salvezza di Forza contro Soglia '+(dice.includes(f.die)?Number(f.die.slice(1))/2+1:'da registrare')+' dal Dado del Frutto '+f.die+') oppure +1 Dado Danno '+w.grado+' del colpo, mai entrambi. Non si applica automaticamente.':'';return {weapon:w,valid:problems.length===0,errors:problems,signature,reach:w.reach||'',attack:(c.attr?.[w.attr]||'Attributo da definire')+' '+w.attr+' + '+w.grado+' Arma Naturale',damage:w.grado+' Arma Naturale',note:'Attacco base: Azione principale. Non richiede Ruolo Combattente o Stile; non concede Tecniche o Talenti di Stile e non occupa l’Arsenale.'};}
 function useProblems(c,t){const f=read(c),out=[];if(f.esaurito&&(t.fonte==='Frutto'||String(t.arma||'').startsWith('natural:')))out.push('Frutto / trasformazioni indisponibili fino al prossimo Riposo Lungo.');if(f.tipo==='Logia'&&f.formaPerduta&&['Singolo','Area'].includes(t.forma))out.push('Forma Perduta già attiva: non consente attacchi, Tecniche offensive o interazione materiale.');if(String(t.arma||'').startsWith('natural:')){const w=naturalWeapons(c,{purpose:'use'}).find(w=>w.id===t.arma);if(w)out.push(...w.errors,...w.operationalErrors);else out.push('L’Arma Naturale collegata non è più disponibile.');}return [...new Set(out)];}
 function sourceIdentity(f){const keys=['identita','creatura','zoanType','subtipo','tipoZoan','scelteTalenti'];const o={};keys.forEach(k=>{if(f[k]!=null&&present(f[k]))o[k]=f[k];});return Object.keys(o).length?o:null;}
 function awakeningProblems(c){const f=read(c),r=f.risveglio||{},out=[];if(!present(c.amb))out.push('Ambizione');if(r.approvatoGM!==true)out.push('Permesso del GM');awakening.forEach(([k,label])=>{if(!present(r[k]))out.push(label);});if(!list(r.famiglie).length||list(r.famiglie).some(v=>!families.includes(v)))out.push('Famiglie del Risveglio');if(f.tipo==='Logia'&&!present(r.ambienteOstile))out.push('Ambiente Ostile');if(f.tipo==='Zoan'&&!present(r.dominante))out.push('Caratteristica Dominante');return out;}
 function dossier(c){const f=read(c);if(!f.has)return null;const sections=[{title:'Scheda di Identità',rows:fields(f,'identita',identity)}],r=rules[f.tipo];
  if(r)sections.push({title:'Tratto e Firma',rows:[{label:'Tratto',value:r.tratto},{label:'Firma',value:r.firma}]});
  const choiceRows=list(choices[f.tipo]).map(([id,name,label])=>({label:name+' · '+label,value:text(f.scelteTalenti?.[id]),id,active:has(c,name)}));if(choiceRows.some(x=>present(x.value)))sections.push({title:'Scelte dei Talenti',rows:choiceRows});
  if(f.tipo==='Zoan'){sections.push({title:'Scheda della Creatura',rows:[{label:'Categoria',value:nature(f)},...fields(f,'creatura',creature),{label:'Forma attuale registrata',value:text(f.forma)},{label:'Famiglia di Movimento',value:text(f.famigliaMovimento)}]});sections.push({title:'Armi Naturali · fuori Arsenale',rows:naturalWeapons(c,{purpose:'use'}).map(w=>({label:w.nome||'Arma Naturale',value:[w.anatomia,w.tipo,w.attr,w.grado,'Forme: '+list(w.forme).join(', '),'Portata: '+(w.portata||'da registrare'),w.reach,w.note].filter(Boolean).join(' · '),warning:w.errors.concat(w.operationalErrors).join(' ')}))});}
  if(f.formaCombattimento)sections.push({title:'Forma di Combattimento · '+(has(c,'Forma di Combattimento')?'Talento acquisito e sbloccato':'Progetto / scelta conservata, Talento non utilizzabile'),rows:fields(f,'formaCombattimento',combat)});
  if(f.risveglio){sections.push({title:'Risveglio · '+(has(c,'Risveglio')?'Talento acquisito e sbloccato':'Progetto / scelta conservata, Talento non utilizzabile'),rows:[...fields(f,'risveglio',awakening),{label:'Famiglie coinvolte',value:list(f.risveglio.famiglie).join(', ')},{label:'Approvazione GM registrata',value:f.risveglio.approvatoGM?'Sì':'Da registrare'},...(f.tipo==='Logia'?[{label:'Ambiente Ostile',value:text(f.risveglio.ambienteOstile)}]:[]),...(f.tipo==='Zoan'?[{label:'Caratteristica Dominante',value:text(f.risveglio.dominante)}]:[])]});}
  return {version:1,nome:f.nome||'',tipo:f.tipo||'',die:f.die||'',desc:f.desc||'',sections,missing:missing(c),exhausted:!!f.esaurito,notes:'Le definizioni registrano possibilità e scelte concordate: non assegnano automaticamente Talenti, effetti del Costruttore o bonus. Le scelte restano conservate se cambiano Tipo, Grado o requisiti. Debolezze: mare, Pietra di Mare, Haki; l’Armamento supera alcune difese, non cancella ogni proprietà del Frutto.'};
 }
 root.GLCFruits=Object.freeze({dice,types,identity,creature,combat,awakening,families,movement,sizes,weaponTypes,forms,choices,rules,has,nature,read,fields,missing,naturalWeapons,naturalAttack,arsenal,useProblems,sourceIdentity,awakeningProblems,dossier});
})(typeof window!=='undefined'?window:globalThis);
