/* Interazioni della plancia; le transazioni passano tutte da GLCStore. */
'use strict';
function shipSelect(label,value,options,onchange){const sel=el('select',{class:'txt','aria-label':label});for(const [v,n] of options)sel.appendChild(el('option',{value:v,text:n}));sel.value=value;sel.onchange=()=>onchange(sel.value);return el('label',{class:'fld'},[el('span',{class:'lab',text:label}),sel]);}
function shipInput(label,value,onchange,type='text',commit=false){const inp=el(type==='textarea'?'textarea':'input',{class:'txt',type:type==='textarea'?null:type,value:value??'','aria-label':label});inp[commit?'onchange':'oninput']=()=>onchange(type==='number'?Number(inp.value):inp.value);return el('label',{class:'fld'},[el('span',{class:'lab',text:label}),inp]);}
function shipCheck(label,checked,onchange){return el('label',{class:'row'},[el('input',{type:'checkbox',checked:!!checked,onchange:e=>onchange(e.target.checked)}),el('span',{text:label})]);}
function shipCrewModal(key){const st=STATIONS.find(x=>x.key===key),draft=JSON.parse(JSON.stringify(S.crew[key]));openModal(stationIcon(key,26)+' '+st.ruolo,()=>{
 const w=el('div'),chars=characters();w.appendChild(shipSelect('Personaggio della ciurma',draft.charId||'',[['','Scheda manuale / PNG'],...Object.entries(chars).map(([id,p])=>[id,p.nome||'Pirata senza nome'])],id=>{draft.charId=id;refreshModal();}));
 if(draft.charId){const c=chars[draft.charId];w.appendChild(el('p',{class:'sub',text:c?'Dadi, Skill e Talenti seguono la scheda salvata del personaggio. Le postazioni non concedono Talenti.':'Personaggio collegato non disponibile: il riferimento è conservato. Scegli esplicitamente un altro operatore.'}));if(c)w.appendChild(el('p',{text:Object.entries(c.attr||{}).map(([a,d])=>a+' '+d).join(' · ')}));}
 else{
  w.appendChild(shipInput('Nome dell’operatore',draft.nome,v=>draft.nome=v));
  const attrs=key==='capitano'?['Spirito','Forza']:key==='combattente'?['Forza','Tecnica']:[GLCShip.stations[key]];
  for(const a of attrs)w.appendChild(shipSelect('Dado '+a,draft.attrs?.[a]||(a===GLCShip.stations[key]?draft.attr:'—'),DICE_ATTR.map(d=>[d,d]),d=>{draft.attrs||={};draft.attrs[a]=d;if(a===GLCShip.stations[key])draft.attr=d;}));
  if(['ingegnere','timoniere','cannoniere'].includes(key)){
   w.appendChild(shipSelect('Stile effettivo dell’operatore',draft.style||'',[['','Nessuno / altro'],['Navigatore','Navigatore'],['Carpentiere','Carpentiere'],['Meccanico','Meccanico']],v=>{draft.style=v;refreshModal();}));
   for(const skill of ['Navigazione','Carpenteria','Meccanica'])w.appendChild(shipSelect('Skill '+skill,draft.skills?.[skill]||(key==='ingegnere'&&skill==='Carpenteria'?S.carpenteria:'—'),DICE_ATTR.map(d=>[d,d]),v=>{draft.skills||={};draft.skills[skill]=v;}));
   if(draft.style){const role=draft.style==='Navigatore'?'Navigatore':'Ingegnere',tree=GLCShipTalents[role]?.styles?.[draft.style];w.appendChild(el('p',{class:'sub',text:'Registra soltanto i Talenti realmente acquisiti. Grado e prerequisiti vengono verificati prima dell’uso.'}));for(const t of tree?.talenti||[]){const id=role+' · '+draft.style+' · '+t.n;w.appendChild(shipCheck(t.n+' ('+t.tier+')',(draft.talents||[]).includes(id),yes=>{draft.talents||=[];draft.talents=yes?[...new Set([...draft.talents,id])]:draft.talents.filter(x=>x!==id);}));}}
  }
 }
 w.appendChild(el('div',{class:'addrow'},[el('button',{class:'btn gold',text:'Salva postazione',onclick:()=>{if(changeShip(s=>s.crew[key]=draft))closeModal();}}),el('button',{class:'btn ghost',text:'Libera postazione',onclick:()=>{if(changeShip(s=>s.crew[key]=GLCShip.blank().crew[key]))closeModal();}})]));return w;
 });}
function shipModuleModal(index,template){const existing=index!==null&&index!==undefined,draft=JSON.parse(JSON.stringify(existing?S.moduli[index]:{...template,id:newId(),installato:true}));draft.parametri||={};openModal('Scheda Modulo navale',()=>{
 const w=el('div');w.appendChild(shipInput('Nome',draft.nome,v=>draft.nome=v));w.appendChild(shipInput('Slot',draft.slot,v=>draft.slot=v,'number'));w.appendChild(shipInput('Effetto / riferimento',draft.eff,v=>draft.eff=v,'textarea'));
 w.appendChild(el('p',{class:'ship-warning',text:'La scheda deve dichiarare attivazione, bersaglio, valore, durata/frequenza, consumi e limiti (§13.16.3). I valori non definiti dal manuale sono parametri concordati con il GM.'}));
 for(const [k,n] of [['attivazione','Attivazione'],['bersaglio','Bersaglio / sistema'],['durata','Durata / frequenza'],['consumi','Consumi'],['limiti','Limitazioni']])w.appendChild(shipInput(n,draft[k]||'',v=>draft[k]=v));
 if(/Timone gemello|Cabina del navigatore|Officina di bordo|Arpioni/i.test(draft.nome))w.appendChild(shipSelect('Dado bonus concordato',draft.parametri.dado||'—',DICE_ATTR.map(d=>[d,d]),v=>draft.parametri.dado=v));
 if(/Stiva ampliata/i.test(draft.nome))w.appendChild(shipInput('Unità di Stiva aggiuntive concordate',draft.parametri.stiva||0,v=>draft.parametri.stiva=v,'number'));
 if(/Chiglia veloce/i.test(draft.nome))w.appendChild(shipInput('Bonus Iniziativa concordato',draft.parametri.iniziativa||0,v=>draft.parametri.iniziativa=v,'number'));
 w.appendChild(shipCheck('Modulo Danneggiato',draft.danneggiato,v=>draft.danneggiato=v));
 w.appendChild(shipCheck('Modulo Guasto (avaria)',draft.guasto,v=>draft.guasto=v));
 w.appendChild(shipCheck('Modulo Distrutto',draft.distrutto,v=>draft.distrutto=v));
 w.appendChild(el('div',{class:'addrow'},[el('button',{class:'btn gold',text:existing?'Salva scheda':'Installa modulo',onclick:()=>{if(changeShip(s=>{if(existing){const old=s.moduli[index];if(!Number.isInteger(draft.slot)||draft.slot<1)throw Error('Slot non validi.');if(GLCShip.slotsUsed(s)-Number(old.slot||1)+draft.slot>GLCShip.slotsTotal(s))throw Error('Slot insufficienti.');s.moduli[index]=draft;}else GLCShip.install(s,draft);}))closeModal();}}),existing?el('button',{class:'btn ghost',text:'Smonta',onclick:()=>{if(changeShip(s=>{s.moduleArchive||=[];s.moduleArchive.push({...s.moduli[index],smontatoIl:new Date().toISOString()});s.moduli.splice(index,1);}))closeModal();}}):null]));return w;
 });}
function shipCatalogModal(){openModal('Catalogo Moduli navali',()=>{const w=el('div');w.appendChild(el('p',{class:'sub',text:'Slot '+slotsUsed()+'/'+slotsTot()+'. Completa i parametri della scheda prima di utilizzare effetti generici.'}));for(const m of CATALOG)w.appendChild(gcard(GLCArt.html(GLCArt.moduleKey(m),44),m.nome,m.slot+' slot',esc(m.eff),()=>shipModuleModal(null,{...m,attivazione:'Secondo scheda',bersaglio:'Sistema della nave',durata:/scena/i.test(m.eff)?'1 volta per scena':/avventura/i.test(m.eff)?'1 volta per avventura':'Secondo effetto',consumi:'Da specificare se previsti',limiti:'Richiede condizioni materialmente possibili'})));w.appendChild(el('button',{class:'btn ghost',text:'Nuovo modulo personalizzato',onclick:()=>shipModuleModal(null,{nome:'',slot:1,eff:''})}));return w;},{wide:true});}
function shipManoeuvreModal(type){let options={total:null,band:S.battle.band??1,collision:false,recoil:null,materials:false,actionAvailable:true,opposed:false,opponent:null,heal:null,threshold:8};openModal('Risolvi '+({cannonate:'Cannonate',evasiva:'Manovra Evasiva',speronamento:'Speronamento',fuga:'Fuga',emergenza:'Riparazione d’Emergenza',traversata:'Traversata'}[type]),()=>{
 const w=el('div'),p=GLCShip.profile(S,type,characters(),options);w.appendChild(el('p',{text:'Tiro: '+p.dice.join(' + ')+(p.threshold?' · Soglia '+p.threshold:'')}));if(p.errors.length)w.appendChild(el('div',{class:'ship-warning',text:p.errors.join(' ')}));
 if(type==='cannonate')w.appendChild(shipSelect('Fascia di distanza',String(options.band),[['0','Accostati · 0–20 m'],['1','Sotto tiro · oltre20–200 m'],['2','In vista · oltre200–600 m'],['3','All’orizzonte · oltre600 m']],v=>{options.band=Number(v);refreshModal();}));
 w.appendChild(shipInput('Totale della Prova',options.total,v=>options.total=v,'number'));w.appendChild(shipCheck('Operatore con Azione disponibile',options.actionAvailable,v=>options.actionAvailable=v));
 if(type==='cannonate'){w.appendChild(el('p',{text:'Danno al bersaglio: '+p.damageDie+(GLCShip.talent(p.character,'Regolazione Fine — Base')?' + '+p.damageDie+' (Regolazione Fine)':'')+'. PS e PV sono scale separate; una cannonata alla nave non danneggia automaticamente la ciurma.'}));if(GLCShip.modules(S,'Cannoni gemelli').length)w.appendChild(shipCheck('Utilizza Cannoni gemelli (1 cannonata extra/scena)',false,v=>options.gemelli=v));}
 if(type==='speronamento'){w.appendChild(shipCheck('Collisione materialmente possibile',options.collision,v=>options.collision=v));w.appendChild(shipInput('Contraccolpo tirato (1d4 PS)',options.recoil,v=>options.recoil=v,'number'));w.appendChild(el('p',{text:'Danno al bersaglio: '+p.damageDie+'. Il contraccolpo si applica comunque.'}));}
 if(type==='fuga'){w.appendChild(shipCheck('Inseguimento: Prova contrapposta',options.opposed,v=>{options.opposed=v;refreshModal();}));if(options.opposed)w.appendChild(shipInput('Totale Vele + Astuzia dell’inseguitrice',options.opponent,v=>options.opponent=v,'number'));w.appendChild(el('p',{class:'sub',text:'Vincere aumenta di una fascia; parità mantiene la distanza. Il fallimento concede una cannonata d’opportunità solo entro portata. Il GM stabilisce quando il contatto è perso.'}));}
 if(type==='emergenza'){w.appendChild(shipCheck('Strumenti e materiali realmente disponibili',options.materials,v=>options.materials=v));w.appendChild(el('p',{text:'Recupero ordinario: '+p.repairDice+' × intero dado Carpenteria '+(GLCShip.skill(p.character,'Carpenteria')||'—')+'. La Firma del Carpentiere raddoppia il totale con margine +4; massimo '+psMax()+' PS.'}));w.appendChild(shipInput('Totale recupero dei dadi (prima della Firma)',options.heal,v=>options.heal=v,'number'));}
 if(type==='traversata'){w.appendChild(shipInput('Soglia stabilita dal GM',options.threshold,v=>options.threshold=v,'number'));w.appendChild(el('p',{class:'sub',text:'Strumenti nautici: Bussola +d4 Mari Blu; Log Pose artigianale +d6 Grand Line; carta aggiornata +d6 prossimo tiro; dettagliata +d8 per3 traversate; Eternal Pose +d10 verso la sua isola. Registra gli strumenti realmente pertinenti e il totale del tiro. Nessun danno fisso per un fallimento.'}));if(S.rotta?.disponibile)w.appendChild(shipCheck('Dichiaro prima del tiro il d6 di Rotta dello stesso viaggio',false,v=>options.route=v));}
 w.appendChild(el('button',{class:'btn gold',text:'Registra manovra',onclick:()=>{let result;if(changeShip(s=>{if(options.total===null)throw Error('Registra il totale della Prova.');if(options.route){if(!s.rotta?.disponibile)throw Error('Dado Rotta non disponibile.');s.rotta.disponibile=false;}result=GLCShip.resolve(s,type,characters(),options);})){closeModal();alert((result.success?'Successo':'Esito non riuscito')+' · margine '+result.margin+(result.signature?' · Firma: recupero ×2':'')+(result.routeDie?' · Conservi1d6 di Rotta; il GM rivela un pericolo reale più avanti.':''));}}}));return w;
 });}
function shipBattlePanel(){const w=el('div');w.appendChild(el('p',{class:'sub',text:'Una Manovra per round e l’Azione dell’operatore. Talenti e Moduli possono concedere eccezioni; due tiri PNG non sono due Manovre.'}));w.appendChild(el('div',{class:'ship-controls'},[el('button',{class:'btn ghost',text:'Inizia battaglia',disabled:S.battle.active,onclick:()=>changeShip(GLCShip.beginBattle)}),el('button',{class:'btn ghost',text:'Nuovo round',disabled:!S.battle.active,onclick:()=>changeShip(GLCShip.beginRound)}),el('button',{class:'btn ghost',text:'Fine battaglia',disabled:!S.battle.active,onclick:()=>changeShip(GLCShip.endBattle)})]));if(S.battle.active)w.appendChild(el('p',{class:'sub',text:'Round '+S.battle.round+' · Manovre eseguite: '+(S.battle.used.join(', ')||'nessuna')}));
 w.appendChild(shipSelect('Distanza attuale',String(S.battle.band??1),[['0','Accostati (0–20 m)'],['1','Sotto tiro (oltre20–200 m)'],['2','In vista (oltre200–600 m)'],['3','All’orizzonte (oltre600 m)']],v=>changeShip(s=>s.battle.band=Number(v))));
 const g=el('div',{class:'gcards one'});for(const [type,name] of [['cannonate','Cannonate'],['evasiva','Manovra Evasiva'],['speronamento','Speronamento'],['fuga','Fuga'],['emergenza','Riparazione d’Emergenza']]){const p=GLCShip.profile(S,type,characters());g.appendChild(gcard(svgIcon({cannonate:'bomb',evasiva:'shield',speronamento:'boat',fuga:'wind',emergenza:'hammer'}[type],26),name,p.dice.join(' + ')+(p.threshold?' · Soglia '+p.threshold:''),p.errors.length?'<span style="color:#e0b84e">'+esc(p.errors.join(' '))+'</span>':'Postazione pronta · utilizza l’Azione',()=>shipManoeuvreModal(type)));}w.appendChild(g);
 if(S.battle.effects.evasiva)w.appendChild(el('button',{class:'btn ghost',text:'Prossima cannonata nemica: Soglia +4 · consumalo',onclick:()=>changeShip(s=>s.battle.effects.evasiva=false)}));
 if(S.battle.criticalPending)w.appendChild(el('button',{class:'btn gold',text:'Ingresso in Critica: registra1d6 Componenti',onclick:()=>shipComponentModal()}));
 w.appendChild(el('p',{class:'sub',text:'Iniziativa navale: '+GLCShip.stat(S,'vele')+' + Astuzia del Timoniere. In combattimento misto: Tecnica + Astuzia dei PG, un round personale = un round navale. A soglia di affondamento il GM comunica cedimento lento3round, rapido1round o catastrofico immediato.'}));return w;}
function shipComponentModal(){let first=null,second=null,key='',note='';openModal('Tiro dei Componenti',()=>{const w=el('div');if(S.battle.componentGM){w.appendChild(el('p',{class:'ship-warning',text:'Anche il secondo tiro indica un componente già danneggiato. Nessun terzo tiro: il GM decide un aggravamento oppure un altro componente esposto.'}));w.appendChild(shipSelect('Altro componente esposto',key,[['','Aggravamento narrativo'],...DESTRUCT.map(d=>[d.key,d.nome])],v=>key=v));w.appendChild(shipInput('Aggravamento deciso dal GM',note,v=>note=v,'textarea'));w.appendChild(el('button',{class:'btn gold',text:'Registra scelta GM',onclick:()=>{if(changeShip(s=>GLCShip.resolveComponentGM(s,key,note)))closeModal();}}));}else{w.appendChild(shipInput('Risultato1d6 (1–6)',first,v=>first=v,'number'));w.appendChild(shipInput('Secondo1d6 solo se il primo era già danneggiato',second,v=>second=v,'number'));w.appendChild(el('button',{class:'btn gold',text:'Applica componente',onclick:()=>{let r;if(changeShip(s=>r=GLCShip.componentRoll(s,first,second))){if(r.gm)refreshModal();else closeModal();}}}));}return w;});}
function shipCargoPanel(){const w=el('div'),st=S.stiva;w.appendChild(el('p',{text:'Capacità: '+GLCShip.capacity(S)+' Unità di Stiva · carico registrato '+((Number(st.cargo)||0)+(Number(st.provviste)||0))+' · indipendente dagli slot Modulo.'}));for(const [k,n] of [['persone','Persone a bordo (ciurma + passeggeri)'],['provviste','Unità di Provviste'],['cargo','Unità di Cargo']])w.appendChild(shipInput(n,st[k],v=>{if(v<0)return;changeShip(s=>s.stiva[k]=v);},'number',true));const need=GLCShip.provisions(st.persone);w.appendChild(el('p',{class:'sub',text:'Consumo ordinario: '+need+' Unità/settimana;1 Unità nutre fino a5 persone. Riduzioni esplicite si applicano prima dell’arrotondamento. Non vengono generate nuove scorte dai Moduli.'}));w.appendChild(el('button',{class:'btn ghost',text:'Consuma1settimana ordinaria',onclick:()=>changeShip(s=>{if(s.stiva.provviste<need)throw Error('Scorte insufficienti: il GM gestisce l’esaurimento, senza danni automatici.');s.stiva.provviste-=need;})}));w.appendChild(el('p',{class:'sub',text:'Cibo preparato e cure restano nella Cambusa e nella scheda del pirata. Un solo pasto ordinario per scena; Aiuto Nakama: un solo dado aiutante per tiro, una volta per scontro/scena, Azione dell’aiutante in combattimento.'}));return w;}
function shipPrint(){const previous=RTAB;RTAB='Stampa';renderShip();const restore=()=>{RTAB=previous;renderShip();window.removeEventListener('afterprint',restore);};window.addEventListener('afterprint',restore);window.print();setTimeout(restore,1000);}
function shipImportDocument(raw){if(!raw||typeof raw!=='object'||Array.isArray(raw))throw Error('Serve una scheda o un archivio di navi.');const archive=raw.ships&&typeof raw.ships==='object'&&!Array.isArray(raw.ships),keys=archive?[...new Set([...(Array.isArray(raw.order)?raw.order:[]),...Object.keys(raw.ships)])].filter(id=>raw.ships[id]):[],imported=archive?keys.map(id=>[id,raw.ships[id]]):[['',raw]],metadata=archive?Object.fromEntries(Object.entries(raw).filter(([k])=>k!=='ships')):null,pending={...NT,ships:{...NT.ships},order:NT.order.slice()};pending.ships[NT.activeId]=S;let active='',mapping={};for(const [sourceId,data] of imported){if(!data||typeof data!=='object'||Array.isArray(data))throw Error('Scheda nave non valida.');const id=newId();pending.ships[id]=GLCShip.normalize({...data,importSource:{...(data.importSource||{}),shipId:sourceId||data.id||null,importatoIl:new Date().toISOString(),...(metadata?{archiveMetadata:metadata}:{})}});pending.order.push(id);mapping[sourceId]=id;active=id;}if(!active)throw Error('Archivio vuoto.');pending.activeId=mapping[raw.activeId]||active;(window.GLCStore||localStorage).setItem(KEY,JSON.stringify(pending));NT=pending;S=GLCShip.normalize(NT.ships[NT.activeId]);renderShipsBar();closeModal();renderShip();}
function shipPresetModal(){let selected='scafo';openModal('Configurazione di partenza',()=>{const w=el('div');w.appendChild(el('p',{class:'ship-warning',text:'Una statistica d8, le altre d6. Questa azione sostituisce soltanto i quattro dadi; conserva danni, risorse, Moduli, ID e dati della nave. I PS non vengono recuperati automaticamente.'}));w.appendChild(shipSelect('Statistica a d8',selected,STAT_DEFS.map(([k,n])=>[k,n]),v=>selected=v));w.appendChild(el('button',{class:'btn gold',text:'Applica configurazione',onclick:()=>{if(changeShip(s=>{for(const k of Object.keys(GLCShip.blank().stats))s.stats[k]=k===selected?'d8':'d6';if(s.psCur>GLCShip.psMax(s))s.psCur=GLCShip.psMax(s);})){closeModal();}}}));return w;});}
function shipPSPanel(){const [cn,col]=condition(),mx=psMax(),bar=el('div',{class:'lbar pv'},[el('div',{class:'lbar-k',text:'Punti Struttura'}),el('div',{class:'lbar-t'},[el('div',{class:'lbar-f',style:'width:'+Math.max(0,Math.min(100,S.psCur/mx*100))+'%;background:'+col})])]),v=el('div',{class:'lbar-v'}),inp=el('input',{class:'txt num',type:'number','aria-label':'Punti Struttura attuali',value:S.psCur});inp.onchange=()=>changeShip(s=>GLCShip.setPS(s,Number(inp.value)));v.appendChild(el('button',{class:'pabtn',text:'−',onclick:()=>changeShip(s=>GLCShip.setPS(s,Number(s.psCur)-1))}));v.appendChild(inp);v.appendChild(el('span',{class:'vsep',text:'/ '+mx}));v.appendChild(el('button',{class:'pabtn',text:'+',onclick:()=>changeShip(s=>GLCShip.setPS(s,Number(s.psCur)+1))}));bar.appendChild(v);bar.appendChild(el('div',{class:'condline',html:'Condizione: <b style="color:'+col+'">'+cn+'</b> · affondamento a '+GLCShip.sinking(S)+'PS · integra>75% · danneggiata>50% · grave>25% · critica'}));return bar;}
function shipDamageSettings(){return shipSelect('Interpretazione GM di «−1 dado» sui componenti',S.penalitaComponenti||'',[['','Da chiarire prima del tiro'],['gradino','Riduci di un gradino (minimo d4)'],['dado','Togli il dado Nave dal pool']],v=>changeShip(s=>s.penalitaComponenti=v));}
function shipCrewTalents(){const w=el('div'),seen=new Set();for(const station of STATIONS){const c=GLCShip.occupant(S,station.key,characters());if(!c)continue;for(const t of GLCTalents.active(c)){if(!['Navigatore','Ingegnere','Cuoco','Capitano'].includes(t.role))continue;const identity=(S.crew[station.key].charId||c.nome)+'|'+t.key;if(seen.has(identity))continue;seen.add(identity);w.appendChild(el('details',{},[el('summary',{text:(c.nome||station.ruolo)+' · '+t.name}),el('p',{class:'sub',text:t.definition.d})]));}}w.appendChild(el('p',{class:'sub',text:'I benefici personali richiedono tutte le condizioni della scheda; Ordini, Azioni, ST, risorse e frequenze restano quelli della capacità. Le postazioni non concedono capacità automaticamente. Le versioni evolute includono soltanto i benefici previsti, senza sommare usi o bonus della versione precedente.'}));return w;}
function shipUpgradeModal(key,next,threshold,materials){let total=null,done=false,port=true,consumed={};openModal('Potenziamento '+key+' → '+next,()=>{const w=el('div'),c=GLCShip.occupant(S,'ingegnere',characters());w.appendChild(el('p',{html:'Soglia '+threshold+' · Prova: '+carpPoolStr()}));w.appendChild(el('p',{class:'ship-warning',text:'Materiali della scheda Portale: '+matStr(materials)+'. Verifica la ricetta e il tempo del progetto con il GM. Un successo migliora soltanto questa statistica; non recupera PS automaticamente.'}));for(const [id,q] of materials)w.appendChild(shipInput('Materiale consumato su fallimento (GM): '+MAT_NAME[id],consumed[id]||0,v=>consumed[id]=v,'number'));w.appendChild(shipInput('Totale Astuzia + Carpenteria',total,v=>total=v,'number'));w.appendChild(shipCheck('Lavoro completato con strumenti, tempo e materiali previsti',done,v=>done=v));w.appendChild(shipCheck('Cantiere in porto',port,v=>port=v));if(GLCShip.talent(c,'Cantiere Viaggiante'))w.appendChild(el('p',{class:'sub',text:'Cantiere Viaggiante: lavoro possibile in mare e in metà tempo. Officina di bordo: −25%ore e il dado dichiarato nella scheda. Il GM concorda cumulo e arrotondamento dei tempi.'}));w.appendChild(el('button',{class:'btn gold',text:'Registra progetto',onclick:()=>{if(changeShip(s=>{const c=GLCShip.occupant(s,'ingegnere',characters());if(s.battle.active)throw Error('Un potenziamento strutturale richiede il Cantiere fuori battaglia.');if(!c||!GLCShip.attributeDice.includes(c.attr?.Astuzia)||!GLCShip.attributeDice.includes(GLCShip.skill(c,'Carpenteria')))throw Error('Assegna un operatore con Astuzia e Carpenteria.');if(!port&&!GLCShip.talent(c,'Cantiere Viaggiante'))throw Error('Il lavoro in mare richiede Cantiere Viaggiante.');if(!done||total===null)throw Error('Completa il progetto e registra la Prova.');if(GLCShip.step(s.stats[key],1)!==next||s.stats[key]==='d12')throw Error('Il progetto non corrisponde al Grado attuale.');for(const [id,q] of materials)if((Number(s.magazzino[id])||0)<q)throw Error('Materiali mancanti: '+MAT_NAME[id]);if(total>=threshold)s.stats[key]=next;for(const [id,q] of materials){const use=total>=threshold?q:Number(consumed[id]||0);if(!Number.isInteger(use)||use<0||use>q)throw Error('Quantità consumata non valida.');s.magazzino[id]-=use;}s.log.push({kind:'potenziamento',stat:key,target:next,total,threshold,success:total>=threshold,materiali:materials,at:new Date().toISOString()});})){closeModal();}}}));return w;});}
function shipImprovementsModal(){let done=false;openModal('Lavori strutturali permanenti',()=>{const w=el('div'),c=GLCShip.occupant(S,'ingegnere',characters());w.appendChild(el('p',{class:'sub',text:'Il beneficio viene registrato soltanto dopo un lavoro completo con materiali, strumenti e tempo. Resta su questa nave quando il Carpentiere scende. Non genera Moduli né recupera PS.'}));w.appendChild(shipCheck('Lavoro completato con strumenti, materiali e tempo concordati',done,v=>done=v));
 const saveImprovement=(key,value,talent)=>{if(changeShip(s=>{if(!done)throw Error('Completa prima il lavoro.');if(!GLCShip.talent(c,talent))throw Error('Il Carpentiere deve possedere il Talento e i prerequisiti.');if(s.miglioramenti[key])throw Error('Questo miglioramento è già registrato sulla nave.');s.miglioramenti[key]=value;s.log.push({kind:'lavoro',talento:talent,operator:S.crew.ingegnere.charId||c.nome,at:new Date().toISOString()});}))refreshModal();};
 for(const [key,n] of [['maestroDeiModuli','Maestro dei Moduli'],['scafoRinforzato','Scafo Rinforzato']])w.appendChild(el('button',{class:'btn ghost',text:n+(S.miglioramenti[key]?' · lavoro già registrato':''),disabled:!!S.miglioramenti[key],onclick:()=>saveImprovement(key,true,n)}));
 for(const [key,n] of [['naveLeggendaria','nave-leggendaria'],['scafoInespugnabile','scafo-inespugnabile']]){const has=c&&GLCPrestige.has(c,n);w.appendChild(el('button',{class:'btn ghost',text:(key==='naveLeggendaria'?'Nave Leggendaria':'Scafo Inespugnabile')+(S.miglioramenti[key]?' · registrato':''),disabled:!has,onclick:()=>{if(changeShip(s=>{if(!done||!GLCPrestige.has(c,n))throw Error('Servono lavoro completo e Talento di Prestigio valido.');const value=GLCPrestige.level(GLCTalents.skillDie(c,'Carpenteria'))===6?2:1;if(Number(s.miglioramenti[key]||0)>=value)throw Error('Lavoro già registrato: il beneficio permanente non diminuisce né si cumula.');s.miglioramenti[key]=value;}))refreshModal();}}));}
 for(const [key,n] of STAT_DEFS)w.appendChild(el('button',{class:'btn ghost',text:'Nave Cresciuta: '+n,disabled:!!S.miglioramenti.naveCresciuta,onclick:()=>{if(changeShip(s=>{if(!done||!GLCShip.talent(c,'Nave Cresciuta'))throw Error('Servono lavoro completo e Talento Nave Cresciuta valido.');if(s.miglioramenti.naveCresciuta)throw Error('Nave Cresciuta è già stata applicata.');if(!GLCShip.dice.includes(s.stats[key])||s.stats[key]==='d12')throw Error('Limite ordinario d12.');s.stats[key]=GLCShip.step(s.stats[key],1);s.miglioramenti.naveCresciuta={stat:key,operator:S.crew.ingegnere.charId||c.nome};}))refreshModal();}}));return w;});}
function shipRepairModal(r){let total=null,ps=null,done=false,consumed={};openModal(r.t,()=>{const w=el('div');w.appendChild(el('p',{text:r.ore+' ore · Soglia '+r.s}));w.appendChild(el('p',{html:'Prova: '+carpPoolStr()}));w.appendChild(el('p',{class:'ship-warning',text:'Ricetta di materiali e conseguenze dettagliate: configurazione storica della campagna. Ore e Soglia: Manuale base. Il GM indica i PS ottenuti coerenti con la condizione; nessun recupero viene inventato automaticamente.'}));w.appendChild(el('p',{text:matStr(r.mat||[])+' · Successo: '+r.ok+' · Fallimento grave: '+r.ko}));for(const [id,q] of (r.mat||[]))w.appendChild(shipInput('Materiale consumato su fallimento (GM): '+MAT_NAME[id],consumed[id]||0,v=>consumed[id]=v,'number'));w.appendChild(shipInput('Totale Astuzia + Carpenteria',total,v=>total=v,'number'));w.appendChild(shipInput('PS finali concordati (solo riparazione scafo)',ps,v=>ps=v,'number'));w.appendChild(shipCheck('Intervento completato; strumenti e materiali della ricetta disponibili',done,v=>done=v));w.appendChild(el('button',{class:'btn gold',text:'Registra intervento',onclick:()=>{if(changeShip(s=>{const c=GLCShip.occupant(s,'ingegnere',characters());if(!c||!GLCShip.attributeDice.includes(c.attr?.Astuzia)||!GLCShip.attributeDice.includes(GLCShip.skill(c,'Carpenteria')))throw Error('Serve un operatore con Astuzia e Carpenteria.');if(!done||total===null)throw Error('Completa il lavoro e registra la Prova.');if(s.battle.active)throw Error('Le riparazioni ordinarie richiedono il Cantiere fuori dalla battaglia.');for(const [id,q] of r.mat||[])if((Number(s.magazzino[id])||0)<q)throw Error('Materiali mancanti: '+MAT_NAME[id]);if(total>=r.s){const comp=DESTRUCT.find(d=>r.t.includes(d.nome)||d.key==='macchine'&&r.t.includes('Sala macchine'));if(comp)GLCShip.setComponent(s,comp.key,false);else{if(ps===null||ps<s.psCur||ps>GLCShip.psMax(s))throw Error('Registra PS finali validi, senza superare il massimo.');if(r.t.includes('danno lieve')&&(s.psCur<=GLCShip.psMax(s)-11||ps-s.psCur>10+(total-r.s>=4?2:0)))throw Error('Il danno lieve riguarda soltanto1–10PS persi; +2PS con margine +4.');const target=r.t.includes('Danneggiata') ? .75 : r.t.includes('Grave') ? .5 : r.t.includes('Critica') ? .25 : 0;if(target&&ps/GLCShip.psMax(s)<=target)throw Error('I PS indicati non raggiungono la condizione prevista dal successo.');GLCShip.setPS(s,ps);}}for(const [id,q] of r.mat||[]){const use=total>=r.s?q:Number(consumed[id]||0);if(!Number.isInteger(use)||use<0||use>q)throw Error('Quantità consumata non valida.');s.magazzino[id]-=use;}s.log.push({kind:'cantiere',intervento:r.t,total,margin:total-r.s,materiali:r.mat,at:new Date().toISOString()});})){closeModal();}}}));return w;});}
