import AssetImage from './asset-image';
'use client';
import {useState,useRef} from 'react';
import {Pencil, Circle, Type, Undo2,Trash2,Save} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import type {Mark} from './design-types';
export function AnnotationMarks({marks}:{marks:Mark[]}){return <>{marks.map(m=>{const a=m.points[0],b=m.points.at(-1);if(!a||!b)return null;return m.tool==='text'?<text key={m.id} x={a.x} y={a.y} fill={m.color} fontSize="27" fontWeight="600" stroke="#111" strokeWidth=".7" paintOrder="stroke">{m.text}</text>:m.tool==='circle'?<ellipse key={m.id} cx={(a.x+b.x)/2} cy={(a.y+b.y)/2} rx={Math.abs(b.x-a.x)/2} ry={Math.abs(b.y-a.y)/2} stroke={m.color} fill="none" strokeWidth="4"/>:<polyline key={m.id} points={m.points.map(p=>p.x+','+p.y).join(' ')} stroke={m.color} fill="none" strokeWidth="4" strokeLinecap="round" strokeLinejoin="round"/>;})}</>}
export default function Annotator({url,title,initial,onSave,onClose}:{url:string;title:string;initial:Mark[];onSave:(marks:Mark[])=>void;onClose:()=>void}){
 const [marks,setMarks]=useState<Mark[]>(structuredClone(initial));const [draft,setDraft]=useState<Mark|null>(null);const draftRef=useRef<Mark|null>(null);const [tool,setTool]=useState<Mark['tool']>('pen');const [color,setColor]=useState('#D6ED9C');const [text,setText]=useState('');const svg=useRef<SVGSVGElement>(null);
 const point=(e:React.PointerEvent)=>{const r=svg.current!.getBoundingClientRect();return{x:Math.max(0,Math.min(1000,Math.round((e.clientX-r.left)/r.width*100000)/100)),y:Math.max(0,Math.min(1000,Math.round((e.clientY-r.top)/r.height*100000)/100))};};
 const finish=()=>{if(draftRef.current)setMarks(ms=>[...ms,draftRef.current!]);draftRef.current=null;setDraft(null);};
 return <Dialog open onOpenChange={v=>!v&&onClose()}><DialogContent className="studio-dialog annotation-dialog"><DialogTitle>Annota · {title}</DialogTitle><DialogDescription>Disegna sul riferimento, evidenzia i dettagli o inserisci una nota. L’immagine originale rimane disponibile.</DialogDescription><div className="feature-toolbar">{([['pen',Pencil,'Disegna'],['circle',Circle,'Cerchia'],['text',Type,'Testo']] as const).map(([key,Icon,label])=><button key={key} className={'soft-button '+(tool===key?'feature-active':'')} onClick={()=>setTool(key)}><Icon size={16}/>{label}</button>)}<input type="color" aria-label="Colore annotazione" value={color} onChange={e=>setColor(e.target.value)}/>{tool==='text'&&<input aria-label="Testo da posizionare" placeholder="Scrivi, poi clicca sull’immagine" value={text} onChange={e=>setText(e.target.value)}/>}<button className="soft-button" onClick={()=>setMarks(ms=>ms.slice(0,-1))}><Undo2 size={16}/>Annulla tratto</button><button className="soft-button" onClick={()=>setMarks([])}><Trash2 size={16}/>Pulisci</button><button className="primary-button" onClick={()=>{onSave(marks);onClose();}}><Save size={16}/>Salva annotazioni</button></div><div className="annotation-scroll"><div className="annotation-image"><AssetImage src={url} alt={title}/><svg ref={svg} viewBox="0 0 1000 1000" preserveAspectRatio="none" aria-label="Superficie per annotare" onPointerDown={e=>{if(tool==='text'){if(text.trim())setMarks(ms=>[...ms,{id:crypto.randomUUID(),tool,color,points:[point(e)],text:text.trim()}]);return;}e.currentTarget.setPointerCapture(e.pointerId);const m:Mark={id:crypto.randomUUID(),tool,color,points:[point(e)]};draftRef.current=m;setDraft(m);}} onPointerMove={e=>{if(!draftRef.current)return;const m={...draftRef.current,points:[...draftRef.current.points,point(e)]};draftRef.current=m;setDraft(m);}} onPointerUp={finish} onPointerCancel={()=>{draftRef.current=null;setDraft(null);}}><AnnotationMarks marks={draft?[...marks,draft]:marks}/></svg></div></div></DialogContent></Dialog>
}
