import {fetchAsset, isForgeAsset, saveVersionAsset} from './cloud-assets';
import {storyText} from './story-data';
import {jsPDF} from 'jspdf';
import type {Board,Mark} from './design-types';
type Picture={data:string;width:number;height:number};
export async function pictureForPDF(url:string,marks:Mark[]=[]):Promise<Picture>{
 const response=await fetchAsset(url);if(!response.ok)throw Error('Un riferimento non è disponibile. Controlla i file prima di esportare.');const blob=await response.blob();const bitmap=await createImageBitmap(blob);const width=Math.min(1500,bitmap.width),height=width*bitmap.height/bitmap.width;const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const ctx=canvas.getContext('2d')!;ctx.fillStyle='#ffffff';ctx.fillRect(0,0,width,height);ctx.drawImage(bitmap,0,0,width,height);bitmap.close();
 for(const m of marks){if(!m.points.length)continue;const a=m.points[0],b=m.points.at(-1)!;ctx.strokeStyle=m.color;ctx.fillStyle=m.color;ctx.lineWidth=Math.max(2,width*.004);ctx.lineJoin='round';ctx.lineCap='round';if(m.tool==='text'){ctx.font=`600 ${width*.027}px sans-serif`;ctx.fillText(m.text||'',a.x/1000*width,a.y/1000*height);}else if(m.tool==='circle'){ctx.beginPath();ctx.ellipse((a.x+b.x)/2000*width,(a.y+b.y)/2000*height,Math.abs(b.x-a.x)/2000*width,Math.abs(b.y-a.y)/2000*height,0,0,Math.PI*2);ctx.stroke();}else{ctx.beginPath();m.points.forEach((p,i)=>i?ctx.lineTo(p.x/1000*width,p.y/1000*height):ctx.moveTo(p.x/1000*width,p.y/1000*height));ctx.stroke();}}
 return {data:canvas.toDataURL('image/jpeg',.9),width,height};
}
async function loadPDFFonts(){const read=async(url:string)=>{const r=await fetch(url);if(!r.ok)throw Error('Caratteri del PDF non disponibili. Riprova.');const bytes=new Uint8Array(await r.arrayBuffer());let value='';for(let i=0;i<bytes.length;i+=8192)value+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(value);};return Promise.all([read('/forgia/fonts/DossierSans.ttf'),read('/forgia/fonts/DossierSans-Bold.ttf')]);}
export async function buildDossier(board:Board,load=pictureForPDF,fonts?:string[]){
 const pdf=new jsPDF({unit:'mm',format:'a4'});const f=fonts||await loadPDFFonts();pdf.addFileToVFS('DossierSans.ttf',f[0]);pdf.addFont('DossierSans.ttf','Dossier','normal');pdf.addFileToVFS('DossierSans-Bold.ttf',f[1]);pdf.addFont('DossierSans-Bold.ttf','Dossier','bold');let y=26;let page=1;
 const clean=(s:unknown)=>String(s??'').replace(/[\u2000-\u206F]/g,'-');
 const header=()=>{pdf.setFont('Dossier','normal');pdf.setFillColor(23,30,29);pdf.rect(0,0,210,15,'F');pdf.setTextColor(217,235,183);pdf.setFontSize(10);pdf.text('FORMA / CHARACTER DOSSIER',16,10);pdf.setTextColor(60,70,70);pdf.setFontSize(9);pdf.text(String(page),194,287,{align:'right'});pdf.setFont('Dossier','normal');};header();
 const room=(h:number)=>{if(y+h>272){const font=pdf.getFont(),size=pdf.getFontSize(),color=pdf.getTextColor();pdf.addPage();page++;header();pdf.setFont(font.fontName,font.fontStyle);pdf.setFontSize(size);pdf.setTextColor(color);y=27;}};
 const line=(text:string,size=11,bold=false)=>{pdf.setFont('Dossier',bold?'bold':'normal');pdf.setFontSize(size);const lines=pdf.splitTextToSize(clean(text),178) as string[];for(const l of lines){room(size*.48+2);pdf.setTextColor(32,41,40);pdf.text(l,16,y);y+=size*.48+2;}y+=3;};
 const image=async(url:string,marks?:Mark[],heading?:string)=>{const p=await load(url,marks);const w=Math.min(178,160*p.width/p.height),h=w*p.height/p.width;room(h+(heading?22:5));if(heading)line(heading,16,true);pdf.addImage(p.data,'JPEG',16,y,w,h,undefined,'FAST');y+=h+7;};
 line(board.name,25,true);line('Dossier di riferimento - '+new Date().toLocaleDateString('it'),10);
 const used=new Set<string>();for(const [label,id]of [['Vista frontale',board.views?.front],['Vista laterale',board.views?.side],['Vista posteriore',board.views?.back]]){const n=board.nodes.find(n=>n.id===id);if(n?.data.url){await image(n.data.url,n.data.annotations,label!+' - '+n.data.title);if(n.data.text)line(n.data.text);used.add(n.id);}}
 const cover=board.nodes.find(n=>n.id===board.coverId);if(cover?.data.url&&!used.has(cover.id)){await image(cover.data.url,cover.data.annotations,'Concept principale');if(cover.data.text)line(cover.data.text);used.add(cover.id);}
 for(const n of board.nodes){if(used.has(n.id))continue;room(n.data.kind==='image'&&n.data.url?190:Math.min(100,35+(n.data.colors?.length||0)*28));line(n.data.title,16,true);if(n.data.groupId){const group=board.nodes.find(g=>g.id===n.data.groupId);if(group)line('Gruppo: '+group.data.title,9);}if(n.data.category)line('Categoria: '+n.data.category,10);if(n.data.status)line('Stato: '+n.data.status,10);if(n.data.kind==='image'&&n.data.url&&!used.has(n.id))await image(n.data.url,n.data.annotations);if(n.data.text)line(n.data.text);if(n.data.story)line(storyText(n.data.story));if(n.data.kind==='model')line('File 3D: '+(n.data.filename||'Non caricato'),10);for(const c of n.data.colors||[]){room(25);pdf.setFillColor(c.hex);pdf.roundedRect(16,y-2,14,10,1,1,'F');y+=14;line(`${c.name} - ${c.hex}${c.part?' | Parte: '+c.part:''}${c.finish?' | Finitura: '+c.finish:''}`,11);if(c.texture)await image(c.texture);}}
 line('Collegamenti',16,true);for(const e of board.edges){const from=board.nodes.find(n=>n.id===e.source)?.data.title,to=board.nodes.find(n=>n.id===e.target)?.data.title;if(from&&to)line(from+' -> '+to,10);}
 return pdf;
}
export async function exportDossier(board:Board){const pdf=await buildDossier(board);pdf.save((board.name.replace(/[^a-zA-Z0-9_-]/g,'-')||'personaggio')+'-dossier.pdf');}
