import {fetchAsset, isForgeAsset, saveVersionAsset} from './cloud-assets';
import AssetImage from './asset-image';
'use client';
import {useEffect,useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Slider} from '@/components/ui/slider';
import {Checkbox} from '@/components/ui/checkbox';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Plus,Save,Copy,RotateCcw,Download,Trash2,Upload} from 'lucide-react';
import {toast} from 'sonner';
import Viewer from './viewer';
import OriginalDownload from './original-download';
import {storyText} from './story-data';
import type {Board,Data} from './design-types';
import {snapshotBoard,restoreNodes} from './board-tools';
import {uploadAsset} from './upload-client';
export function Choice({value,onChange,options,label}:{value?:string;onChange:(v:string)=>void;options:{id:string;name:string}[];label:string}){return <Select value={value||'none'} onValueChange={v=>onChange(v==='none'?'':v)}><SelectTrigger aria-label={label}><SelectValue placeholder={label}/></SelectTrigger><SelectContent><SelectItem value="none">{label}</SelectItem>{options.map(o=><SelectItem key={o.id} value={o.id}>{o.name}</SelectItem>)}</SelectContent></Select>}
function Preview({board}:{board:Board}){return <div className="version-preview"><h3>{board.name}</h3>{board.nodes.filter(n=>n.data.kind!=='group').map(n=><article key={n.id}><strong>{n.data.title}</strong>{n.data.kind==='image'&&n.data.url&&<AssetImage src={n.data.url} alt={n.data.title}/>}<p>{n.data.text}</p>{n.data.story&&<p>{storyText(n.data.story)}</p>}{n.data.colors&&<div className="swatches">{n.data.colors.map((c,i)=><div key={i} style={{background:c.hex}} title={c.name}/>)}</div>}{n.data.kind==='model'&&<small>{n.data.filename||'Modello da caricare'}</small>}</article>)}</div>}
export default function FeatureWorkspace({mode,board,change,variant,onClose}:{mode:string;board:Board;change:(fn:(b:Board)=>Board)=>void;variant:(b:Board)=>void;onClose:()=>void}){
 const images=board.nodes.filter(n=>n.data.kind==='image'&&n.data.url);const models=board.nodes.filter(n=>n.data.kind==='model'&&n.data.url);const [imageId,setImageId]=useState(board.coverId||images[0]?.id||'');const [modelId,setModelId]=useState(models[0]?.id||'');const [preset,setPreset]=useState('front');const [versionName,setVersionName]=useState('');const [busy,setBusy]=useState(false);const [left,setLeft]=useState('current');const [right,setRight]=useState(board.versions?.at(-1)?.id||'current');const [compared,setCompared]=useState<{a?:Board;b?:Board}>({});
 const title:any={views:'Viste sincronizzate',compare:'Confronto 2D–3D',versions:'Versioni e varianti',materials:'Palette e materiali',groups:'Gruppi di nodi',trash:'Cestino dei nodi'};
 const view=board.views||{};const viewChange=(v:any)=>change(b=>({...b,views:{...b.views,...v}}));
 async function readVersion(id:string){if(id==='current')return board;const entry=board.versions?.find(v=>v.id===id);if(!entry)throw Error('Versione non trovata');const r=await fetchAsset(entry.url);if(!r.ok)throw Error('Impossibile leggere la versione');const data=await r.json() as Board;if(!Array.isArray(data.nodes)||!Array.isArray(data.edges))throw Error('Versione non valida');return data;}
 useEffect(()=>{if(mode!=='versions')return;let cancelled=false;setCompared({});Promise.all([readVersion(left),readVersion(right)]).then(([a,b])=>{if(!cancelled)setCompared({a,b});}).catch(e=>toast.error(e.message));return()=>{cancelled=true;};},[left,right,mode,board]);
 async function saveVersion(source:Board,name:string){const data=await saveVersionAsset(snapshotBoard(source));return {id:crypto.randomUUID(),date:new Date().toISOString(),name,url:data.url};}
 const options=images.map(n=>({id:n.id,name:n.data.title}));
 return <Dialog open onOpenChange={v=>!v&&onClose()}><DialogContent className="studio-dialog feature-dialog"><DialogTitle>{title[mode]} · {board.name}</DialogTitle><DialogDescription>{mode==='versions'?'Conserva una revisione, confronta due versioni o crea una variante indipendente.':mode==='views'?'Assegna i riferimenti. Zoom e spostamento verticale sono condivisi fra le tre viste.':'Tutti i dettagli restano collegati a questo personaggio.'}</DialogDescription>
 {mode==='views'&&<><div className="feature-toolbar"><label className="range-field">Zoom {view.zoom||100}%<Slider min={25} max={250} step={5} value={[view.zoom||100]} onValueChange={([v])=>viewChange({zoom:v})}/></label><label className="range-field">Allineamento verticale<Slider min={-40} max={40} value={[view.y||0]} onValueChange={([v])=>viewChange({y:v})}/></label><button className="soft-button" onClick={()=>viewChange({zoom:100,y:0})}><RotateCcw size={15}/>Ripristina</button></div><div className="views-grid">{(['front','side','back'] as const).map((key,i)=>{const img=images.find(n=>n.id===view[key]);return <div key={key}><h3>{['Frontale','Laterale','Posteriore'][i]}</h3><Choice value={view[key]} onChange={v=>viewChange({[key]:v})} options={options} label="Scegli riferimento"/><div className="reference-viewport">{img?<AssetImage src={img.data.url} alt={img.data.title} style={{transform:`translateY(${view.y||0}%) scale(${(view.zoom||100)/100})`}}/>:<p>Assegna un’immagine dalla tela</p>}</div></div>;})}</div></>}
 {mode==='compare'&&<><div className="feature-toolbar"><span>Vista del modello</span>{['front','side','back','perspective'].map(v=><button className={'soft-button '+(v===preset?'feature-active':'')} key={v} onClick={()=>setPreset(v)}>{({front:'Fronte',side:'Profilo',back:'Retro',perspective:'Prospettiva'} as any)[v]}</button>)}</div><div className="comparison-grid"><section><Choice value={imageId} onChange={setImageId} options={options} label="Riferimento 2D"/><div className="reference-viewport">{images.find(n=>n.id===imageId)?<AssetImage src={images.find(n=>n.id===imageId)!.data.url} alt="Riferimento 2D"/>:<p>Aggiungi un riferimento alla tela</p>}</div></section><section><Choice value={modelId} onChange={setModelId} options={models.map(n=>({id:n.id,name:n.data.title}))} label="Modello 3D"/><Viewer key={modelId} url={models.find(n=>n.id===modelId)?.data.url} name={models.find(n=>n.id===modelId)?.data.filename} preset={preset}/></section></div><p className="feature-help">Trascina per ruotare. Usa le viste rapide per confrontare silhouette e proporzioni.</p></>}
 {mode==='versions'&&<><div className="feature-toolbar"><input placeholder="Nome della revisione" aria-label="Nome della revisione" value={versionName} onChange={e=>setVersionName(e.target.value)}/><button disabled={busy} className="primary-button" onClick={async()=>{setBusy(true);try{const v=await saveVersion(board,versionName.trim()||'Revisione '+((board.versions?.length||0)+1));change(b=>({...b,versions:[...(b.versions||[]),v]}));setVersionName('');setRight(v.id);toast.success('Versione conservata');}catch(e:any){toast.error(e.message);}finally{setBusy(false);}}}><Save size={16}/>Salva versione</button></div><div className="version-list">{board.versions?.map(v=><div key={v.id}><span><strong>{v.name}</strong><small>{new Date(v.date).toLocaleString('it')}</small></span><button disabled={busy} className="soft-button" onClick={async()=>{setBusy(true);try{variant(await readVersion(v.id));toast.success('Variante creata nella home');}catch(e:any){toast.error(e.message);}finally{setBusy(false);}}}><Copy size={15}/>Crea variante</button><button disabled={busy} className="soft-button" onClick={async()=>{setBusy(true);try{const old=await saveVersion(board,'Prima del ripristino · '+new Date().toLocaleString('it'));const restored=await readVersion(v.id);change(b=>({...restored,id:b.id,versions:[...(b.versions||[]),old],trash:b.trash}));toast.success('Versione ripristinata; la precedente è stata conservata');}catch(e:any){toast.error(e.message);}finally{setBusy(false);}}}><RotateCcw size={15}/>Ripristina</button></div>)||<p>Nessuna versione salvata.</p>}</div><div className="comparison-grid">{[left,right].map((v,i)=><section key={i}><Choice value={v} onChange={i===0?setLeft:setRight} options={[{id:'current',name:'Versione attuale'},...(board.versions||[]).map(v=>({id:v.id,name:v.name}))]} label="Scegli versione"/>{(i===0?compared.a:compared.b)&&<Preview board={(i===0?compared.a:compared.b)!}/>}</section>)}</div></>}
 {mode==='materials'&&<div className="materials-workspace">{board.nodes.filter(n=>n.data.kind==='palette').map(n=><section key={n.id}><h3>{n.data.title}</h3>{n.data.colors?.map((c,i)=>{const changeColor=(data:any)=>change(b=>({...b,nodes:b.nodes.map(node=>node.id===n.id?{...node,data:{...node.data,colors:node.data.colors!.map((x,j)=>j===i?{...x,...data}:x)}}:node)}));return <div className="material-detail" key={i}><input type="color" aria-label="Colore materiale" value={c.hex} onChange={e=>changeColor({hex:e.target.value})}/><label className="field">Nome<input value={c.name} onChange={e=>changeColor({name:e.target.value})}/></label><label className="field">Parte del personaggio<input placeholder="Mantello, occhi…" value={c.part||''} onChange={e=>changeColor({part:e.target.value})}/></label><label className="field">Finitura<input placeholder="Opaco, satinato, metallo…" value={c.finish||''} onChange={e=>changeColor({finish:e.target.value})}/></label><label className="texture-upload">{c.texture?<AssetImage src={c.texture} alt={'Texture '+c.name}/>:<Upload size={22}/>}<span>Texture</span><input type="file" accept="image/png,image/jpeg,image/webp" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{const a=await uploadAsset(f);changeColor({texture:a.url,textureFilename:f.name});toast.success('Texture caricata');}catch(err:any){toast.error(err.message);}}}/></label><OriginalDownload url={c.texture} filename={c.textureFilename} label="Scarica texture"/></div>;})}</section>)}{!board.nodes.some(n=>n.data.kind==='palette')&&<p>Crea un nodo Palette nella tela per associare colori, parti, finiture e texture.</p>}</div>}
 {mode==='groups'&&<div className="groups-workspace"><p className="feature-help">Assegna i nodi ai gruppi. Nella tela puoi selezionarne più di uno con Ctrl/Cmd + clic. Il pulsante sul gruppo richiude o mostra tutti i suoi elementi.</p><button className="soft-button" onClick={()=>change(b=>({...b,nodes:[...b.nodes,{id:crypto.randomUUID(),type:'studio',position:{x:50,y:50},data:{kind:'group',title:'Nuovo gruppo'}}]}))}><Plus size={16}/>Nuovo gruppo</button>{board.nodes.filter(n=>n.data.kind==='group').map(group=><section key={group.id}><label className="field">Nome del gruppo<input value={group.data.title} onChange={e=>change(b=>({...b,nodes:b.nodes.map(n=>n.id===group.id?{...n,data:{...n.data,title:e.target.value}}:n)}))}/></label><div className="group-members">{board.nodes.filter(n=>n.data.kind!=='group').map(n=><label key={n.id}><Checkbox checked={n.data.groupId===group.id} onCheckedChange={checked=>change(b=>({...b,nodes:b.nodes.map(x=>x.id===n.id?{...x,data:{...x.data,groupId:checked?group.id:undefined}}:x)}))}/>{n.data.title}</label>)}</div></section>)}</div>}
 {mode==='trash'&&<div className="version-list">{board.trash?.length?board.trash.map(t=><div key={t.id}><span><strong>{t.name}</strong><small>{new Date(t.date).toLocaleString('it')}</small></span><button className="soft-button" onClick={()=>change(b=>restoreNodes(b,t.id))}><RotateCcw size={16}/>Ripristina nodi e legami</button></div>):<p>Il cestino dei nodi è vuoto.</p>}</div>}
 </DialogContent></Dialog>
}
